### ISSUE TITLE
Create flow for verifying email ownership on profile creation and edit

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4476] opened 2024-07-24 17:28 UTC
@WhyldWanderer was checking our subscriber list in Ortto and found many users have fake emails in their profiles which makes it difficult to communicate with them about their project's status or opportunities/campaigns they should be aware of. 

This issue is for designing a flow that requires users to validate their email address while either creating their Giveth profile for the first time or changing their email address when editing their profile info. 

## Requirements

- on profile creation users can enter email address into input box
- user clicks a button which triggers sending an email with a verification code
- user enters code sent in email into an input box on update profile view
- inputting the correct code will successfully verify their email address
- user can successfully update their profile information when email address is verified, they do not need to reload the page to recheck if it's been verified
- user cannot save their profile with unverified email address
- users can save their profile without an email address if they **do not** own any projects
- user can see a visual confirmation (green chark mark or smthng) when their email is verified
- users cannot use an email that has already been verified in another profile for any other profile (user address -> email address relationship is unique)
- Solana and Ethereum lists of verified emails are treated separately. The same email address can be verified for ONE user on Ethereum and ONE user connecting with Solana (we handle this in case it's the same user on different networks).

### for current users 

- all existing users will need to verify their email address with flow 
- users cannot manage their existing projects until they verify their email address - we treat is as an incomplete profile
- unique message is shown for existing users when editing their profile prompting them to verify their email address
- if an existing user does not own any projects they can remove their email address and save their profile.

## Flow 
1. User goes to My Profile
2. Clicks on update Profile
3. Enters email address
4. Clicks Verify Email button
5. BE generates verification code and sends it in email
6. User receives Verification code to email entered
7. User copies verification code from email and enters it into input field 
8. BE checks if code is valid
9. If code is valid then user receives confirmation and the email is considered verified
10. user clicks save profile, receives toast notif that info has been saved

https://github.com/user-attachments/assets/949e833b-1262-457e-a523-800f15a3a96f

## Figma
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3068-66717&t=TTng1YwgiqprVvdc-1

## AC

- [ ] new user can successfully verify email on create profile flow
- [ ] existing user can successfully verify email on edit profile flow
- [ ] users can still donate and boost projects without needing to verify or enter email address
- [ ] user CANNOT create project without verified email address
- [ ] user cannot access projects from my projects page without verified email address
- [ ] user cannot edit project directly from project url without verified email address 
- [ ] yellow banner is shown when user logs in without verified email address and owns at least 1 project
- [ ] clicking "Verify Email" on yellow banner link redirects user to edit profile modal on "my account" page
- [ ] yellow banner is NOT shown when user has verified email address
- [ ] Solana and Ethereum lists of verified emails are treated separately. The same email address can be verified for ONE user on Ethereum and ONE user connecting with Solana (we handle this in case it's the same user on different networks).
- [ ] email copy is correct and contains verification code
- [ ]  Ethereum user cannot use email that has already been verified by another ethereum account 
- [ ]  Solana user cannot use email that has already been verified by another Solana account

**Comment by Tosinolawale** [comment] 2024-07-24 20:48
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3069-66987&t=7DZN7YOa8X4HDscB-1
@divine-comedian 
Created a flow here. Check it out

**Comment by Tosinolawale** [comment] 2024-08-01 19:22
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3068-66717&t=TTng1YwgiqprVvdc-1
[Email Verification Giveth.webm](https://github.com/user-attachments/assets/949e833b-1262-457e-a523-800f15a3a96f)
Attached with Video showing prototype

**Comment by jainkrati** [comment] 2024-08-02 07:24
Looping in @ae2079 to do the research on the packages available, under review from @RamRamez

**Comment by RamRamez** [comment] 2024-08-03 22:40
@jainkrati We already have this service in impact-graph and notification-center service for project verification form and I think we can use those services for this task. Also we can use same Ortto template, so I believe this issue is straightforward.

**Comment by ae2079** [comment] 2024-08-04 22:02
> Looping in @ae2079 to do the research on the packages available, under review from @RamRamez

I've checked the existing code and done some research, and I think we can handle email verification using our Ortto client without adding new packages. We can generate random codes, save them in Redis with an expiration time, and create a /verify-email endpoint. I'll also update the front-end to support this flow. This approach keeps things simple and efficient with our current setup.

**Comment by ae2079** [comment] 2024-08-06 14:07
@divine-comedian 
As I should spend all of my capacity on the Qacc project, I can not do this issue in the next 6 weeks, so I unassigned this issue from myself

**Comment by RamRamez** [comment] 2024-08-07 10:43
@Reshzera Could you please take this issue?
It's more of a front-end task. We already have email verification in impact-graph and notification-center, so may need only minor changes on them.
Please ping me and we can have a short call.

cc @jainkrati

**Comment by Reshzera** [comment] 2024-08-07 11:42
@RamRamez Sure

**Comment by RamRamez** [comment] 2024-08-08 14:57
In email verification step in the form verification design, we didn't had a code to confirm, we used JWT secret that is sent with email address, and when user opens the link in the email, the email address will be automatically confirmed. I believe it's better to have a consistent design in the app for email confirmation.

@Tosinolawale is it possible to change the design, so removing code input and instead telling user to check their email.
because otherwise we need a new Ortto template, need some changes on notification-center for new Ortto template, and we need to implement verification with code in impact-graph, it will add at least 2 days of devs work.

@divine-comedian WDYT?

<img width="613" alt="image" src="https://github.com/user-attachments/assets/2eac563b-83f5-4c35-a2ad-c7667c1af092">

**Comment by Tosinolawale** [comment] 2024-08-08 15:57
> In email verification step in the form verification design, we didn't had a code to confirm, we used JWT secret that is sent with email address, and when user opens the link in the email, the email address will be automatically confirmed. I believe it's better to have a consistent design in the app for email confirmation.
> 
> @Tosinolawale is it possible to change the design, so removing code input and instead telling user to check their email. because otherwise we need a new Ortto template, need some changes on notification-center for new Ortto template, and we need to implement verification with code in impact-graph, it will add at least 2 days of devs work.
> 
> @divine-comedian WDYT?
> 
> <img alt="image" width="613" src="https://private-user-images.githubusercontent.com/73441857/356272787-2eac563b-83f5-4c35-a2ad-c7667c1af092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzI3MzcsIm5iZiI6MTcyMzEzMjQzNywicGF0aCI6Ii83MzQ0MTg1Ny8zNTYyNzI3ODctMmVhYzU2M2ItODNmNS00YzM1LWEyYWQtYzc2NjdjMWFmMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE1NTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NmQ3ZWM3NGIxYWQ0ZjdmM2FkOTU0MTA0OGFjNjJlN2NhYjA4Y2Y2OWI1ZWY0MGRlYmQ4NDhhZjlhNjQzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YrnwusMLh39YRl7ishQOT8xxB9Evb5CZ-fs28zDkq20">

Email Verification was the Initial design but @divine-comedian brought up issues of email verifications from Multisig account. Either works fine for me, So just let me know what the final decision is in terms of feasibility

**Comment by divine-comedian** [comment] 2024-08-09 20:42
@RamRamez - I would like to get rid of the current email verification step inside of project verification form and instead have this verify step using a code, but that's a later issue.

As Tosin mentioned we have had issues with multisig users not being able to verify their project because of needing to load an external link outside of the giveth safe app. In addition, the UX of sending another link in an email is sort of confusing, the user clicks the link from their email and now has another browser window open with their verification form open - which one do they proceed from?? 

I believe the code is the best way to go forward, I acknowledge the extra work it adds. Is there an existing package or code template that we can use for sending and verifying codes with email addresses? This is a quite common pattern we see on most web apps with login.

This issue I would say is lower on the priority list so if there is more pressing work then let's code this feature when it seems reasonable.

**Comment by RamRamez** [comment] 2024-08-09 22:01
@divine-comedian I got it. So we need to change the current email verification process in impact-graph.

@Reshzera Could you please investigate how we can implement this new feature in impact-graph? Is there a good library/package out there to reduce development work?

**Comment by Reshzera** [comment] 2024-08-12 12:03
@RamRamez Sure I'll take a look

**Comment by divine-comedian** [comment] 2024-08-13 20:55
@Reshzera here is the code snippet you can use to trigger the activity in ortto 

```
"activities": [
		{
			"activity_id": "act:cm:email-verification-code",
			"attributes": {
				"int:cm:code": 1723565874,
				"str:cm:email": "example string value",
				"str:cm:userid": "example string value"
			},
			"fields": {
				"str::email": "contact@email.com"
				"str:cm:user-id": "example string value"
			},
		}
	],
}`;

```

**Comment by RamRamez** [comment] 2024-08-20 22:23
@Reshzera told me he has removed email verification from FE in project verification form, now, we don't these fields from project_verification_form table on BE nor on FE:
`emailConfirmed, emailConfirmationToken, emailConfirmationTokenExpiredAt, emailConfirmationSent, emailConfirmationSentAt, emailConfirmedAt, email`

So, if we remove those fields from DB, those changes are not backward compatible and we should be careful and should handle FE and BE releases at same time.

Or, we can only remove it from UI and keep DB as is, it's safe and fast to do.

@CarlosQ96 @mohammadranjbarz WDYT?

**Comment by mohammadranjbarz** [comment] 2024-08-21 08:27
> @Reshzera told me he has removed email verification from FE in project verification form, now, we don't these fields from project_verification_form table on BE nor on FE: `emailConfirmed, emailConfirmationToken, emailConfirmationTokenExpiredAt, emailConfirmationSent, emailConfirmationSentAt, emailConfirmedAt, email`
> 
> So, if we remove those fields from DB, those changes are not backward compatible and we should be careful and should handle FE and BE releases at same time.
> 
> Or, we can only remove it from UI, remove that step from BE, and keep DB as is, it's safe and fast to do.
> 
> @CarlosQ96 @mohammadranjbarz WDYT?

I do agree

**Comment by Reshzera** [comment] 2024-08-21 12:04
Ok, thanks for the help guys, so just to confirm, I'll let this columns on the DB and just change the validation on the verification form?

**Comment by RamRamez** [comment] 2024-08-21 15:07
@Reshzera Yes you can start. I think you can't only remove it from UI, because you need to disable email verification step from BE too, so, it's still not backward compatible.
You can either only do necessary changes and keep DB intact for now and remove those fields from DB later, or you can do them all at once. It's up to you.

**Comment by mohammadranjbarz** [comment] 2024-08-22 12:04
@Reshzera says he afraid to mess up something while implementing  the backend side of this issue, so he needs someone who knows the backend and DB entities continue his work, as I'm busy with givEconomy things, @CarlosQ96   can you continue his work (this is Rafael WIP branch https://github.com/Giveth/impact-graph/tree/feat/issue-4476)?

**Comment by maryjaf** [comment] 2024-08-26 09:08
I see some open pull request on this issue, Is this ready for testing ? @Reshzera

**Comment by divine-comedian** [comment] 2024-10-01 17:28
@HrithikSampson do you mind picking up this issue? It was mostly finished before rafael left us - I think there is a PR that should be investigated and the code that's been already written. 

@mohammadranjbarz can also provide you some guidance

**Comment by kkatusic** [comment] 2024-11-14 13:52
@divine-comedian, one question, what we will do if user enter email address that already exist inside DB? We can inside dApp have unique wallet address, but not emails. thx

**Comment by divine-comedian** [comment] 2024-11-15 04:17
> @divine-comedian, one question, what we will do if user enter email address that already exist inside DB? We can inside dApp have unique wallet address, but not emails. thx

Part of the feature is that we begin to enforce unique verified emails 

users will need to verify their email to regain access to manage their projects, the flows are included in the figma file that Tosin shared above. 

Unverified emails (ones already in the DB) can be duplicates, since we will need to handle users who might have several user profiles and allow them to transitions to verified emails without creating conflicts.

However once an email is verified another user cannot try to verify that same email to another user profile.  After a reasonable amount of time ~6-9 months we might consider wiping unverified emails from the DB to keep things clean and remove unused or illegitimate email addresses from our mailing contacts. 

One thought that how we handle Solana profiles and Ethereum profiles, since we require the same person to have a different user for solana vs. ethereum we may want to consider solana users and ethereum users to have separate email lists, allowing the same person to use the same email for their solana profile and ethereum profile. WDYT?

**Comment by kkatusic** [comment] 2024-11-16 13:24
Thx @divine-comedian , I understand flow, saw video and everything is ok with that.

Let see about Solana profiled, question for @aminlatifi or @MohammadPCh : do we treat same email with one Solana and one Ethereum wallet as same user or different user? thx

**Comment by divine-comedian** [comment] 2024-11-19 14:47
> Thx @divine-comedian , I understand flow, saw video and everything is ok with that.
> 
> Let see about Solana profiled, question for @aminlatifi or @MohammadPCh : do we treat same email with one Solana and one Ethereum wallet as same user or different user? thx

IIRC we treat them as different users

**Comment by aminlatifi** [comment] 2024-11-19 15:13
> Thx @divine-comedian , I understand flow, saw video and everything is ok with that.
> 
> Let see about Solana profiled, question for @aminlatifi or @MohammadPCh : do we treat same email with one Solana and one Ethereum wallet as same user or different user? thx

Yeah, as I remember we consider them as different users.

**Comment by kkatusic** [comment] 2024-11-20 13:00
> Yeah, as I remember we consider them as different users.

thx @aminlatifi for response ;)

**Comment by kkatusic** [comment] 2024-11-22 12:32
@maryjaf, cc @divine-comedian, let's test it.

1. First test case is for current users that had already account on dApp, they need to go to account page and _edit profile_.
2. Second test is verification for new users.

@maryjaf you have also option inside administration to check/uncheck email verification, to test each case.

Code is robust, we needed to implement changes on 3 repositories.

big thx here @RamRamez. @MohammadPCh and special thx to @CarlosQ96 for all provided information and guidelines

**Comment by maryjaf** [comment] 2024-11-24 11:13
- [ ] 1- The timer for resending the code isn’t set, and it should be displayed in the UI to prevent the user from tapping the button repeatedly.
____________

- [ ] 2- I haven’t verified this email "maryam.jafarymehr@gmail.com"before; I only used it for my account (unverified). However, I receive an error stating that the email is already verified.
"This email that has already been verified on another profile!"
![image](https://github.com/user-attachments/assets/09baba57-b0df-4a90-8a69-ca2d30bd7bdc)
_____________

- [ ] 3-The "Email not verified" message in the Create Project flow isn’t clear. We should guide the user on how to verify their email in this flow. Currently, the user may think there is an email address field in the Create Project flow.
![image](https://github.com/user-attachments/assets/43dabbff-314c-447e-9551-9ec26d985dd2)

_____________

- [ ]  4-A generic error message is shown for all types of errors. For example, if the code is incorrect, the user should be informed specifically that the code is invalid.

![image](https://github.com/user-attachments/assets/0d937dc6-5546-4c37-86bf-26c356e9cb09)

_____


- [ ]  5-The "Save" button should not be enabled until the user enters a correct 5-digit code.
![image](https://github.com/user-attachments/assets/9a5c4b3d-beb0-4cd9-a702-f888f0b84f25)

___________

- [ ] 6- What is the code expiration time? This information should be communicated to the user.

________


- [ ] 7- An Internal Server Error occurs even when I enter the correct code.

![image](https://github.com/user-attachments/assets/16e3d67c-24a0-4095-9f8f-f256fae3542c)


@kkatusic

**Comment by maryjaf** [comment] 2024-11-24 11:53
- [ ] 8- 
- I completed the verification flow for this email marymehr669@gmail.com
- I changed the status of "is verified" filed from Yes to No
- but I still see the "Email Verified" badge in user profile 

https://github.com/user-attachments/assets/cba08878-91ca-4bc9-be37-56b507216245

**Comment by maryjaf** [comment] 2024-11-24 12:02
> * Solana and Ethereum lists of verified emails are treated separately. The same email address can be verified for ONE user on Ethereum and ONE user connecting with Solana (we handle this in case it's the same user on different networks).

- [ ] 9- It seems it doesn't work as expected , I couldn't use an verified email on ethereum user for solana user as well

**Comment by maryjaf** [comment] 2024-11-24 12:18
> * users can save their profile without an email address if they **do not** own any projects

- [ ] 10- this AC doesn't work 

verify email is permanent for all users now


https://github.com/user-attachments/assets/16e688f3-67bb-4926-a453-eb35bfe04e5e

**Comment by maryjaf** [comment] 2024-11-25 07:46
- [ ]  9- when the user's email isn't verified, in project page user can tap on  your project or add an update , is that accepted? @divine-comedian @kkatusic 

https://github.com/user-attachments/assets/df31f53c-5a86-4ad8-9303-b7ea08be4b75

**Comment by kkatusic** [comment] 2024-11-25 08:33
@maryjaf thx for testing, one question about timer, there isn't any mention about adding timer to email verification?

**Comment by maryjaf** [comment] 2024-11-25 08:37
> @maryjaf thx for testing, one question about timer, there isn't any mention about adding timer to email verification?

Yeah , it's just a suggestion to prevent users to tap on resend button repeatedly.

**Comment by maryjaf** [comment] 2024-11-25 09:16
- [ ] 11- when user isn't signed in this banner is shown in public project page view

![image](https://github.com/user-attachments/assets/95db846a-99db-4ed1-878d-532bd1c7f6bc)

**Comment by maryjaf** [comment] 2024-11-25 10:51
Shouldn't the button name be "Resend Verification Code!" instead of "Resend Verification Link!"?

![image](https://github.com/user-attachments/assets/f31be490-6eef-4a7e-8d98-d81bf4cf65d2)

**Comment by kkatusic** [comment] 2024-11-25 12:51
> > * Solana and Ethereum lists of verified emails are treated separately. The same email address can be verified for ONE user on Ethereum and ONE user connecting with Solana (we handle this in case it's the same user on different networks).
> 
> * [ ]  7- It seems it doesn't work as expected , I couldn't use an verified email on ethereum user for solana user as well

This will @divine-comedian response. We threat that users as different users and if one have one email, second one can't use same email.

**Comment by kkatusic** [comment] 2024-11-25 12:53
> > * users can save their profile without an email address if they **do not** own any projects
> > * if an existing user does not own any projects they can remove their email address and save their profile.
> 
> * [x]  8- these ACs don't work as expected
> 
> verify email is permanent for all users now
> 
>  Screen.Recording.2024-11-24.at.3.46.57.PM.mov

this was changed after, we added email verification to new users.

**Comment by maryjaf** [comment] 2024-11-25 13:15
please tell me which problems be fixed in last pr then after testing I'll checkbox them as resolved @kkatusic

**Comment by kkatusic** [comment] 2024-11-25 13:16
> please tell me which problems be fixed in last pr then after testing I'll checkbox them as resolved @kkatusic

Ok, than I first need to uncheck it all :D

**Comment by kkatusic** [comment] 2024-11-25 14:08
@maryjaf here what is fixed for now:

1. Timer hasn't included in this verification flow.
2. Fixed.
3. @divine-comedian will decide what we will tell user.
4. Button "Save" disabled.
5. Timer hasn't included in this verification flow.
6. Fixed.
7. Two different wallet address inside dApp are not same user, that's why you can't verify another account.
8. Yes, now verification process is obligatory for all users.
9. @divine-comedian will decide about this.
10. Fixed.
11. Fixed.
12. ... need to think about this
13. Fixed

**Comment by kkatusic** [comment] 2024-11-25 14:08
> Shouldn't the button name be "Resend Verification Code!" instead of "Resend Verification Link!"?
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/389492936-f31be490-6eef-4a7e-8d98-d81bf4cf65d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDIxMTAsIm5iZiI6MTczMjU0MTgxMCwicGF0aCI6Ii8xMTE1MjkxODUvMzg5NDkyOTM2LWYzMWJlNDkwLTZlZWYtNGE3ZS04ZDk4LWQ4MWJmNGNmNjVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxMzM2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTc0ODQzYmUwMGQwYzk4MDhkNjBjODRlM2EyZjFiYTdhNzcwYTEyMzVlZTdmNWIwNjQxMWQwYTYzYWNkNTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d6JYGtywSnqah_XUQqcsVenjs4VvHVLMBF2m-OtOYyM)

This is also fixed.

**Comment by maryjaf** [comment] 2024-11-25 14:38
> * 4-The "Save" button should not be enabled until the user enters a correct 5-digit code.

It hasn't been fixed @kkatusic 

https://github.com/user-attachments/assets/caf2ce3c-ee01-4057-948c-a02a2e328e8a

**Comment by maryjaf** [comment] 2024-11-25 15:14
> * 7. Two different wallet address inside dApp are not same user, that's why you can't verify another account.

could you please tell me more about it that how can I test it @kkatusic

**Comment by divine-comedian** [comment] 2024-11-25 16:52
@maryjaf @kkatusic 

For 

## 9 
 User should not be able to do anything on their project until email is verified, we should disable button for givbacks eligiblity form, adding recipient addresses and the button for submitting a project update should be disabled. 

Based on your feedback we should add hover tooltip on buttons with copy text 
> Edit your profile from "My Account" and verify your email address to continue.

## 10 
Correct, we should not show banner when user is viewing project page of a project they DO NOT own. In case of any conflicts the verify email banner should be shown priority over QF donation match verification banner.

**Comment by divine-comedian** [comment] 2024-11-25 20:13
@kkatusic 

Two things: 

## ONE
It was in requirements (and we spoke about it) that we should handle allowing users to verify email on ethereum and allow user to verify the same email on solana account. 

Imagine you are the same person using Giveth, you log in using Ethereum, verify your email and manage some projects. 

Now you log out and log back in on Solana, you are the same person but you need to verify with a different email just to manage your Solana projects, even though you are the same person.

## TWO
Additionally I noticed when I am on "My account" page I see banner to verify my email, clicking the banner link does nothing. giveth this I think we should add the trigger we spoke of which can open the modal, we should apply this trigger to all views that include this banner with the link.

[Screencast from 2024-11-25 14-13-19.webm](https://github.com/user-attachments/assets/1a193d06-5533-4d12-9dd1-b9f7dc23028b)

**Comment by maryjaf** [comment] 2024-11-26 10:09
> ## 10
> Correct, we should not show banner when user is viewing project page of a project they DO NOT own. In case of any conflicts the verify email banner should be shown priority over QF donation match verification banner.

Thanks @divine-comedian 
now this banner is shown only in project owner view, but one question in the below situation(like as the pic) only verify email banner should be shown? or the current view is ok?

![image](https://github.com/user-attachments/assets/dc21414b-4819-4849-a9c8-0dced2a33fd9)

**Comment by maryjaf** [comment] 2024-11-26 10:15
> ## 9
> User should not be able to do anything on their project until email is verified, we should disable button for givbacks eligiblity form, adding recipient addresses and the button for submitting a project update should be disabled.

The boost button, editing GIVpower table and actions related to recurring donation(deposit,withdraw,end, edit ..) also should be disabled?

https://github.com/user-attachments/assets/6d58d313-4320-47af-b71d-81d11f5fea56

**Comment by divine-comedian** [comment] 2024-11-26 14:15
> > ## 10
> > Correct, we should not show banner when user is viewing project page of a project they DO NOT own. In case of any conflicts the verify email banner should be shown priority over QF donation match verification banner.
> 
> Thanks @divine-comedian now this banner is shown only in project owner view, but one question in the below situation(like as the pic) only verify email banner should be shown? or the current view is ok?
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/389898756-dc21414b-4819-4849-a9c8-0dced2a33fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MzA0MjUsIm5iZiI6MTczMjYzMDEyNSwicGF0aCI6Ii8xMTE1MjkxODUvMzg5ODk4NzU2LWRjMjE0MTRiLTQ4MTktNDg0OS1hOWM4LTBkY2VkMmEzM2ZkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxNDA4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2EyM2EyNDg0OGQxYzU1NTNlMWM2ZjdhOTk1ZDFjM2U0NjcxMDRiY2EwYWEwYTczZjcyNTNjODM4NWMxNmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2qJ5rqVyM6tjiLEs5ZtwCZfvv6PK517AfwIdAkOvdcU)

We should show the verify email banner priority - over the donation matching banner

**Comment by kkatusic** [comment] 2024-11-26 21:15
@maryjaf you can test tomorrow all requested changes and let me know, thx

**Comment by maryjaf** [comment] 2024-11-27 10:05
- [ ] The edit modal is shown once, but when tapping again on "Update Your Profile," the edit user modal does not appear. I think this happens because the link is not updated(opencheck=true) when the modal is closed. @kkatusic 

https://github.com/user-attachments/assets/b0c8ec72-4d6c-455e-ae1a-d39d4fb477a4

- [ ] 
Is the following behavior acceptable? After signing in, this modal is displayed automatically without tapping the "Update My Profile" button.
@divine-comedian @kkatusic

https://github.com/user-attachments/assets/fd629245-8733-473d-af50-ef40ee217d3d

**Comment by maryjaf** [comment] 2024-11-27 10:07
- [ ] by tapping on "Save" button the edit user modal is displayed again
@kkatusic 

https://github.com/user-attachments/assets/638966e8-2a1c-4572-be7a-ea909b99a4f6

**Comment by maryjaf** [comment] 2024-11-27 10:10
- [ ] the color of email address field is red , is this accepted? 

![image](https://github.com/user-attachments/assets/c39337c4-5430-49a0-ae99-495993499673)

**Comment by maryjaf** [comment] 2024-11-27 10:24
> ##
> User should not be able to do anything on their project until email is verified, we should disable button for givbacks eligiblity form, adding recipient addresses and the button for submitting a project update should be disabled.
> 
**> Based on your feedback we should add hover tooltip on buttons with copy text**
> 
**> > Edit your profile from "My Account" and verify your email address to continue.**

- [ ] the button related to verification form is enable for users with notactive email and also the hover tooltip isn't shown
please take a look on below screen record 
@kkatusic 

https://github.com/user-attachments/assets/8d628522-767e-42f6-be6b-b96d611d2c00

**Comment by kkatusic** [comment] 2024-11-27 10:31
> * [ ]  the color of email address field is red , is this accepted?
> 

This is accepted by design flow

**Comment by maryjaf** [comment] 2024-11-27 11:36
> ![image](https://private-user-images.githubusercontent.com/67759413/389635466-ff61672d-7747-4c26-8987-aad00647b709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MzYxODEsIm5iZiI6MTczMjYzNTg4MSwicGF0aCI6Ii82Nzc1OTQxMy8zODk2MzU0NjYtZmY2MTY3MmQtNzc0Ny00YzI2LTg5ODctYWFkMDA2NDdiNzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE1NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MWMxYjA3ODQxNjVhYWUwODMzZTU4ZTQxM2RlNTkzMzY5N2VjZjY1YzdhNTdiZDczZmMwOWJhYmI0Y2Y1ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r0tb4_CafJM2-SCqYFfOWKe0W4dcUDUGtrVdgFxPS20)
> 
> Button Edit Profile -> redirects user to "My Account" page and opens Edit profile modal

Thanks @kkatusic It has been resolve, but one question update or edit profile is final?

![image](https://github.com/user-attachments/assets/f5c96865-58f3-4982-ab0d-7c446490750b)

**Comment by maryjaf** [comment] 2024-11-27 11:53
> > * Solana and Ethereum lists of verified emails are treated separately. The same email address can be verified for ONE user on Ethereum and ONE user connecting with Solana (we handle this in case it's the same user on different networks).
> 
> * [x]  7- It seems it doesn't work as expected , I couldn't use an verified email on ethereum user for solana user as well

Thanks @kkatusic It has been fixed

**Comment by kkatusic** [comment] 2024-11-27 13:32
@maryjaf you can test again, thx ;)

**Comment by maryjaf** [comment] 2024-11-27 14:59
> [ ] the button related to verification form is enable for users with notactive email and also the hover tooltip isn't shown
> please take a look on below screen record
> @kkatusic

- [ ] hover tooltip isn't shown for "Update" tab
 and I think the current tooltip isn't shown in right place  @kkatusic 

https://github.com/user-attachments/assets/12e6d09e-87ac-4f28-ba2a-0e53b91f55ba


- [ ] these buttons shouldn't be disabled in public view 


https://github.com/user-attachments/assets/4b130e07-740a-4ede-823e-deedb2ea41a2

**Comment by kkatusic** [comment] 2024-11-28 13:11
@maryjaf let's go again ;)

**Comment by maryjaf** [comment] 2024-12-01 07:26
> * [x]  hover tooltip isn't shown for "Update" tab
> * [x]  these buttons shouldn't be disabled in public view

Thanks @kkatusic these two problems have been fixed

Could you please check this ? by tapping on boost button nothing happens 
I'm not sure if it is related to this change or not 

https://github.com/user-attachments/assets/54dbd07a-9e73-4f00-9275-9a43002864df

**Comment by kkatusic** [comment] 2024-12-01 11:13
> > * [x]   hover tooltip isn't shown for "Update" tab
> > * [x]   these buttons shouldn't be disabled in public view
> 
> Thanks @kkatusic these two problems have been fixed
> 
> Could you please check this ? by tapping on boost button nothing happens I'm not sure if it is related to this change or not
> Screen.Recording.2024-12-01.at.10.49.10.AM.mov

You can't boost your project before you verify your email

**Comment by maryjaf** [comment] 2024-12-01 11:16
> You can't boost your project before you verify your email

but this project isn't mine 
and I tested this with users with/without verified email, it didn't work for both

**Comment by kkatusic** [comment] 2024-12-02 14:14
@maryjaf let's go again ;)

**Comment by maryjaf** [comment] 2024-12-02 14:46
Thank @kkatusic The boost problem has been fixed

**Closed** 2024-12-09 14:07 UTC
Labels: email
