### ISSUE TITLE
Error on Staking with Permit xDAI/FOX farm -  NOT_VALID_CALL_SIGNATURE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3420] opened 2023-11-21 14:00 UTC
**Describe the bug**
When users try to stake an LP in the xDAI/FOX farm the transaction is failing - The error is coming from the UnipoolTokenDistributor contract and says `UnipoolTokenDistributor: NOT_VALID_CALL_SIGNATURE`

 https://dashboard.tenderly.co/tx/gnosis-chain/0xb61995a18f956bf81c7e535c29d30463339bb667247f35aafeaaf0fe05336bd1

**To Reproduce**
1. Go to GIVfarm on xDAI
2. Create xdai/fox lp on honeyswap
3. Click stake 
4. toggle 'Permit Mode' on
5. stake some tokens
6. see error in metamask
7. proceed anyway
8. see failed tx in tenderly

**Expected behavior**
The user should be able to successfuly stake their LP tokens with Permit mode enabled

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/72a53536-1da9-4506-b03e-3d1c9e7c6481)

**Desktop (please complete the following information):**
 - OS: Ubunutu 22.04
 - Browser: Brave
 - Wallet: MetaMask

**Additional context**
Reported on production by Shapeshift users

**Comment by divine-comedian** [comment] 2023-12-01 14:48
cc: @laurenluz

**Comment by laurenluz** [comment] 2023-12-01 15:07
the rewards on the fox/xDAI farm I believe have ended as of yesterday from [this PR](https://github.com/Giveth/giv-token-contracts/pull/90) they started on May 30.

would have been great to see this issue before! what's the story here?

**Comment by laurenluz** [comment] 2023-12-04 15:07
I mean that I see Krati was assigned, then Ramin, then after my comment Ramin set an estimate... so it looks to me like there is some conversation & coordination going out outside of this issue that I'm not in the loop on... 

This farm needs to be archived. I will make a new issue for that... but we should disable the stake function anyway, so this issue is kind of irrelvant unless we deploy a new regen farm or reactive/extend this.

**Comment by divine-comedian** [comment] 2023-12-04 19:28
> I mean that I see Krati was assigned, then Ramin, then after my comment Ramin set an estimate... so it looks to me like there is some conversation & coordination going out outside of this issue that I'm not in the loop on...
> 
> This farm needs to be archived. I will make a new issue for that... but we should disable the stake function anyway, so this issue is kind of irrelvant unless we deploy a new regen farm or reactive/extend this.

I think it's handled on any unipool contract or any GIVeconomy contract that can call stakeWithPermit @aminlatifi would know more tbh. but actually this only affects the farms - not our GIVpower contract IIRC.

**Comment by aminlatifi** [comment] 2023-12-05 08:08
It's a frontend issue, the permit value is not computed correctly! I think after refactorings, the code snippet was responsible for computing the permission is touched and it's generating a wrong value. Compared with the old implementation or old successful `stakeWithPermit` transactions, it will be totally clear.

**Comment by aminlatifi** [comment] 2023-12-11 06:18
This may help if we cannot use our old code snippet for calculating the permit value
https://github.com/vacekj/wagmi-permit?utm_source=substack&utm_medium=email#readme

**Comment by MoeNick** [comment] 2024-01-18 08:22
What's the status of this issue? is it p1 or p2? or even p0 ? or is it resolved?

**Comment by divine-comedian** [comment] 2024-01-18 13:40
AFAIK not fixed

**Comment by jainkrati** [comment] 2024-03-20 13:50
If there are no regen farms using this , making this a p2. @RamRamez pls work on this once p0,p1 issues are done.

**Comment by jainkrati** [comment] 2024-05-06 13:17
@MohammadPCh pls take this up

**Comment by jainkrati** [comment] 2024-06-03 10:23
@MohammadPCh pls guide @kkatusic to take this up

**Comment by aminlatifi** [comment] 2024-06-09 09:15
@kkatusic The very problem is the `stakeWithPermit` method is now called with an invalid permit value. It used to be working in older versions like this
https://github.com/Giveth/giveth-dapps-v2/blob/bf4e56c8312ad044636ccb2d7c83b04ed99eeea8/src/lib/stakingPool.ts
The problem can be reproduced with any farming contract with `stkeWithPermit` method, including new unipool givpower contracts deployed on OP mainnet.

**Comment by aminlatifi** [comment] 2024-06-12 13:20
Sample of working stake with permit
https://gnosisscan.io/tx/0x801ecb80e130765822518416633174b5e42a1a7ad1d0e75ab4c003a05f3506e4

**Comment by MohammadPCh** [comment] 2024-06-12 18:06
@kkatusic I fixed the Permit functionality, can you check it, and if it is ok continue this task and add the toggle button and handle to the StakeGIV modal and change the states?

**Comment by kkatusic** [comment] 2024-06-12 19:47
> @kkatusic The very problem is the `stakeWithPermit` method is now called with an invalid permit value. It used to be working in older versions like this https://github.com/Giveth/giveth-dapps-v2/blob/bf4e56c8312ad044636ccb2d7c83b04ed99eeea8/src/lib/stakingPool.ts The problem can be reproduced with any farming contract with `stkeWithPermit` method, including new unipool givpower contracts deployed on OP mainnet.

@aminlatifi just to notice here it wasn't error on optimism network it was problem on gnosis network.

**Comment by kkatusic** [comment] 2024-06-12 19:52
> @kkatusic I fixed the Permit functionality, can you check it, and if it is ok continue this task and add the toggle button and handle to the StakeGIV modal and change the states?

Excellent @MohammadPCh , it is working, @divine-comedian you can also check, image is bellow:

![Screenshot 2024-06-12 at 21 46 07](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/73e7a637-3c09-4e5b-9cd9-cdbd85b4992f)

**Comment by kkatusic** [comment] 2024-06-12 19:53
And @divine-comedian missing image from your example:

![Screenshot 2024-06-12 at 21 52 22](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/b9775083-e7e6-430e-8861-bfaa5d8807b1)

**Comment by aminlatifi** [comment] 2024-06-17 13:37
> @divine-comedian @aminlatifi Can we show the permit toggle on all the stake cards, or are there some that do not support this feature?

It depends on the farm, most of them support it except the Gnosis GIVPower. A rule of thumb is to look at the contract and check it has `stakeWithPermit` method or no!

**Comment by maryjaf** [comment] 2024-06-23 08:52
Is it ready for testing @MohammadPCh @kkatusic

**Comment by maryjaf** [comment] 2024-06-23 08:52
Is it ready for testing @MohammadPCh @kkatusic

**Comment by kkatusic** [comment] 2024-06-24 11:18
> Is it ready for testing @MohammadPCh @kkatusic

@maryjaf It it ready ;) , thx

**Comment by maryjaf** [comment] 2024-06-27 07:39
> **Describe the bug** When users try to stake an LP in the xDAI/FOX farm the transaction is failing - The error is coming from the UnipoolTokenDistributor contract and says `UnipoolTokenDistributor: NOT_VALID_CALL_SIGNATURE`
> 
> https://dashboard.tenderly.co/tx/gnosis-chain/0xb61995a18f956bf81c7e535c29d30463339bb667247f35aafeaaf0fe05336bd1
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to GIVfarm on xDAI
> 2. Create xdai/fox lp on honeyswap
> 3. Click stake
> 4. toggle 'Permit Mode' on
> 5. stake some tokens
> 6. see error in metamask
> 7. proceed anyway
> 8. see failed tx in tenderly
> 
> **Expected behavior** The user should be able to successfuly stake their LP tokens with Permit mode enabled
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/67759413/284602478-72a53536-1da9-4506-b03e-3d1c9e7c6481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzI4ODIsIm5iZiI6MTcxOTQ3MjU4MiwicGF0aCI6Ii82Nzc1OTQxMy8yODQ2MDI0NzgtNzJhNTM1MzYtMWRhOS00NTA2LWIwM2UtM2QxYzllN2M2NDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA3MTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Nzk3YTZhZDhmMDdmOWVlODhlMWYxYzdiMDU4N2FlZGQ0Y2UyN2JhOTJiMjczMDNjZjQxZmExMjIwMjQ0MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBT7tj0yuZ6L3ik5IeaAhXBEl1Tx1Yx93IpjIi1oTS8)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubunutu 22.04
> * Browser: Brave
> * Wallet: MetaMask
> 
> **Additional context** Reported on production by Shapeshift users

How can I test  and reproduce theses steps ? I didn't see this lp on stg  xdai/fox

**Comment by kkatusic** [comment] 2024-06-27 10:56
> > **Describe the bug** When users try to stake an LP in the xDAI/FOX farm the transaction is failing - The error is coming from the UnipoolTokenDistributor contract and says `UnipoolTokenDistributor: NOT_VALID_CALL_SIGNATURE`
> > https://dashboard.tenderly.co/tx/gnosis-chain/0xb61995a18f956bf81c7e535c29d30463339bb667247f35aafeaaf0fe05336bd1
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to GIVfarm on xDAI
> > 2. Create xdai/fox lp on honeyswap
> > 3. Click stake
> > 4. toggle 'Permit Mode' on
> > 5. stake some tokens
> > 6. see error in metamask
> > 7. proceed anyway
> > 8. see failed tx in tenderly
> > 
> > **Expected behavior** The user should be able to successfuly stake their LP tokens with Permit mode enabled
> > **Screenshots** ![image](https://private-user-images.githubusercontent.com/67759413/284602478-72a53536-1da9-4506-b03e-3d1c9e7c6481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzI4ODIsIm5iZiI6MTcxOTQ3MjU4MiwicGF0aCI6Ii82Nzc1OTQxMy8yODQ2MDI0NzgtNzJhNTM1MzYtMWRhOS00NTA2LWIwM2UtM2QxYzllN2M2NDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA3MTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Nzk3YTZhZDhmMDdmOWVlODhlMWYxYzdiMDU4N2FlZGQ0Y2UyN2JhOTJiMjczMDNjZjQxZmExMjIwMjQ0MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBT7tj0yuZ6L3ik5IeaAhXBEl1Tx1Yx93IpjIi1oTS8)
> > **Desktop (please complete the following information):**
> > 
> > * OS: Ubunutu 22.04
> > * Browser: Brave
> > * Wallet: MetaMask
> > 
> > **Additional context** Reported on production by Shapeshift users
> 
> How can I test and reproduce theses steps ? I didn't see this lp on stg xdai/fox

@maryjaf go to this [file](https://github.com/Giveth/giveth-dapps-v2/blob/develop/src/config/production.tsx) find xdai/fox, change starting date and ending date, if you need help contact me.

**Comment by maryjaf** [comment] 2024-06-27 12:48
It seems that this issue cannot be tested on the stage environment and needs to be tested on production

**Comment by MohammadPCh** [comment] 2024-07-01 11:46
@maryjaf  you can test it with GIV on Optimism and OP sepolia.

**Comment by divine-comedian** [comment] 2024-07-08 16:50
@kkatusic - can we set this up to be able to be tested on staging properly? let's try setting up a test regenfarm for the next 2 months to give sufficient testing window

**Comment by kkatusic** [comment] 2024-07-09 09:13
@divine-comedian let's try, Cherik isn't available but I think who can help, us, Amin.

@aminlatifi can you help. us with this? Can you check this setup for staging server are contracts address correct:[ link to config file](https://github.com/Giveth/giveth-dapps-v2/blob/b2f4d1ff5732fa75c5fc3332112127586c2ebc36/src/config/development.tsx#L296)
if everything ok I can provide new timelines for that xdai/fox staking.
Also you will need to provide some test tokens to Maryjaf :)

Thx in advance

**Comment by aminlatifi** [comment] 2024-07-09 13:09
> @divine-comedian let's try, Cherik isn't available but I think who can help, us, Amin.
> 
> @aminlatifi can you help. us with this? Can you check this setup for staging server are contracts address correct:[ link to config file](https://github.com/Giveth/giveth-dapps-v2/blob/b2f4d1ff5732fa75c5fc3332112127586c2ebc36/src/config/development.tsx#L296) if everything ok I can provide new timelines for that xdai/fox staking. Also you will need to provide some test tokens to Maryjaf :)
> 
> Thx in advance

@kkatusic Extended/activated fox/dai farm on staging for 14 days.
https://github.com/Giveth/giveth-dapps-v2/pull/4395
cc @divine-comedian @maryjaf

**Comment by kkatusic** [comment] 2024-07-09 14:16
> > @divine-comedian let's try, Cherik isn't available but I think who can help, us, Amin.
> > @aminlatifi can you help. us with this? Can you check this setup for staging server are contracts address correct:[ link to config file](https://github.com/Giveth/giveth-dapps-v2/blob/b2f4d1ff5732fa75c5fc3332112127586c2ebc36/src/config/development.tsx#L296) if everything ok I can provide new timelines for that xdai/fox staking. Also you will need to provide some test tokens to Maryjaf :)
> > Thx in advance
> 
> @kkatusic Extended/activated fox/dai farm on staging for 14 days. #4395 cc @divine-comedian @maryjaf

Thx @aminlatifi , great, it is working now on staging, @maryjaf you can rest it.

**Comment by maryjaf** [comment] 2024-07-09 14:52
In my tests the sign request is shown twice in permit mode and after that I could stake, please check below screen record 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c9c4f58a-adbe-46c9-9782-d01bd996ce9c

**Comment by divine-comedian** [comment] 2024-07-09 14:59
@kkatusic - looks like there is also an issue with the "permit mode" text colour

**Comment by kkatusic** [comment] 2024-07-09 15:25
> In my tests the sign request is shown twice in permit mode and after that I could stake, please check below screen record
> 
>  Screen.Recording.2024-07-09.at.6.18.33.PM.mov

If I understand right Amin and Cherik you for permit staking needs two confirmation.

**Comment by divine-comedian** [comment] 2024-07-09 17:08
> > In my tests the sign request is shown twice in permit mode and after that I could stake, please check below screen record
> > Screen.Recording.2024-07-09.at.6.18.33.PM.mov
> 
> If I understand right Amin and Cherik you for permit staking needs two confirmation.

No, there is an error here, I tested it as well - it is asking for the signature twice - you sign the first signature request, then it bugs out. You need to click STAKE again then it asks for the same signature another time, once you sign the 2nd time around then it generates the actual stake tx and the transaction proceeds as normal

**Comment by kkatusic** [comment] 2024-07-11 12:21
@divine-comedian, yes you are right it is asking you signature two times. I have been started working on this issue, but than Cherik needed to complete it because a lot of stack-related code had to be replaced.

But I will take a look and see is there any fast fix.

**Comment by kkatusic** [comment] 2024-07-11 13:15
> @divine-comedian, yes you are right it is asking you signature two times. I have been started working on this issue, but than Cherik needed to complete it because a lot of stack-related code had to be replaced.
> 
> But I will take a look and see is there any fast fix.

@divine-comedian I made fix, Ramin will check code

**Comment by kkatusic** [comment] 2024-07-11 13:21
@maryjaf please test it when you have time

**Comment by maryjaf** [comment] 2024-07-14 06:44
Thanks @kkatusic I've tested "permit mode" and also"approve mode", the problem has been fixed.

**Comment by kkatusic** [comment] 2024-07-14 08:09
> Thanks @kkatusic I've tested "permit mode" and also"approve mode", the problem has been fixed.

Excellent, thx @maryjaf

**Comment by aminlatifi** [comment] 2024-07-22 11:53
@kkatusic @MohammadPCh I try to use permit mode on optimism and get this error

<img width="646" alt="image" src="https://github.com/user-attachments/assets/e981de0b-96ef-4daf-83cd-266951973db5">

**Comment by kkatusic** [comment] 2024-07-22 14:29
> @kkatusic @MohammadPCh I try to use permit mode on optimism and get this error
> 
> <img alt="image" width="646" src="https://private-user-images.githubusercontent.com/5684607/350954891-e981de0b-96ef-4daf-83cd-266951973db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTg2NzEsIm5iZiI6MTcyMTY1ODM3MSwicGF0aCI6Ii81Njg0NjA3LzM1MDk1NDg5MS1lOTgxZGUwYi05NmVmLTRkYWYtODNjZC0yNjY5NTE5NzNkYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTQyNjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzlkYzU5NTBjY2U4NTE5YjZjMzlhYTQ5MDcwMjEyZTZhMTBlN2Q4MjY5ZGFiYzIwYjFjNGZjNDNhNGE2ZDA5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ksr47V1D_1b_p2jYJtLjmRcwP9PuwJ7DEkhoNK6ujJo">

@aminlatifi you tested on staging or production? thx

**Comment by kkatusic** [comment] 2024-07-22 15:37
@aminlatifi we didn't push this to the production yet

**Comment by laurenluz** [comment] 2024-07-24 09:13
when will this get fixed? I'm noticing the issue too on prod trying to stake w/ permit

**Comment by laurenluz** [comment] 2024-07-24 09:13
Uploading Screen Recording 2024-07-24 at 11.09.44 AM.mov…

**Comment by maryjaf** [comment] 2024-07-24 09:48
This bug has been fixed on staging but hasn't been merged on prod

**Comment by laurenluz** [comment] 2024-07-24 12:04
yes but when will it get merged? @maryjaf

**Comment by kkatusic** [comment] 2024-07-24 21:20
@MohammadPCh can you provide information when this issue would be fixed on production? thx

**Comment by laurenluz** [comment] 2024-07-31 12:18
was this merged already with out qf hotfixes? @MohammadPCh

**Comment by MohammadPCh** [comment] 2024-07-31 13:31
@kkatusic @LatifatAbdullahi I'll check it and keep you posted.

**Comment by MohammadPCh** [comment] 2024-08-01 12:08
@kkatusic I'm a little bit busy today. do you have time to check it today?

**Comment by kkatusic** [comment] 2024-08-01 12:44
> @kkatusic I'm a little bit busy today. do you have time to check it today?

I will check

**Comment by maryjaf** [comment] 2024-08-01 13:03
It hasn't been deployed on production

![image](https://github.com/user-attachments/assets/984ea893-3c07-4b45-a099-3adbea7d8feb)

**Comment by kkatusic** [comment] 2024-08-02 16:22
@aminlatifi, cc @maryjaf, @MohammadPCh, I checked this error. When testing on staging everything is working fine, but when testing on production we got error _Permit signature failed_. 

Error is happening when signature wants to include _nonce_ hash data and it got null value. That nonce data has been fetched data from _nonces_ function inside contract, on production contract that function isn't exist: [link to contract](https://optimistic.etherscan.io/address/0x528cdc92eab044e1e39fe43b9514bfdab4412b98#code) but same function exist on the staging: [link to contract](https://sepolia-optimism.etherscan.io/address/0x2f2c819210191750f2e11f7cfc5664a0eb4fd5e6#code)

I don't know what is right flow of this and why these two contract aren't same. Please can you look at that.

Thx in advance

**Comment by aminlatifi** [comment] 2024-08-05 14:26
> @aminlatifi, cc @maryjaf, @MohammadPCh, I checked this error. When testing on staging everything is working fine, but when testing on production we got error _Permit signature failed_.
> 
> Error is happening when signature wants to include _nonce_ hash data and it got null value. That nonce data has been fetched data from _nonces_ function inside contract, on production contract that function isn't exist: [link to contract](https://optimistic.etherscan.io/address/0x528cdc92eab044e1e39fe43b9514bfdab4412b98#code) but same function exist on the staging: [link to contract](https://sepolia-optimism.etherscan.io/address/0x2f2c819210191750f2e11f7cfc5664a0eb4fd5e6#code)
> 
> I don't know what is right flow of this and why these two contract aren't same. Please can you look at that.
> 
> Thx in advance

You are right @kkatusic 
Basically, not all erc20 tokens support `transferWithPermit`. As it seems, OP Mainnet canonical bridge mints token without that capability. So, we have to disable that feature on optimism mainnet chain.

**Comment by laurenluz** [comment] 2024-08-05 15:09
Who can disable it then? it's been so many weeks now of people reporting this issue. is @kkatusic working on it? @MohammadPCh? @aminlatifi ? :)

**Comment by MohammadPCh** [comment] 2024-08-05 15:19
@laurenluz Thanks for following up, @kkatusic will fix it soon.

**Comment by laurenluz** [comment] 2024-08-05 15:20
thanks guys!!

**Comment by maryjaf** [comment] 2024-08-06 06:39
Thanks,
"permit mode" has been removed on OP network on production.

**Closed** 2024-08-06 06:39 UTC
Labels: bug, P2
