### ISSUE TITLE
GIVfarm APRs on other chains should show up when connected to any chain -  BUG

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4593] opened 2024-08-20 15:36 UTC
When connected to OP Mainnet, I see the GIVfarm APRs on OP Mainnet, but not on Gnosis chain. We used to have it so that I could see all APRs, no matter what chain.. this is the reason we show the other card in general.

@mohammadranjbarz can you check it out as tech lead or assign the right person?

![image](https://github.com/user-attachments/assets/3538d92a-b84c-4404-bd11-67693de5416c)

cc @maryjaf @LatifatAbdullahi

**Comment by mohammadranjbarz** [comment] 2024-08-20 18:15
@laurenluz Will check it and let you know

**Comment by laurenluz** [comment] 2024-09-04 03:15
@mohammadranjbarz can you check this again please? it would be good to fix, now that users are looking at the page from zkevm launch

**Comment by mohammadranjbarz** [comment] 2024-09-23 12:03
> @mohammadranjbarz can you check this again please? it would be good to fix, now that users are looking at the page from zkevm launch

I couldn't find the problem and fix it, can someone with more experience in FE work on that?
@RamRamez  @MohammadPCh  I would appreciate it if you can take this issue

**Comment by laurenluz** [comment] 2024-09-25 12:09
@RamRamez can you work on this this week? P0

**Comment by RamRamez** [comment] 2024-09-25 12:47
@laurenluz The APR for all three chains are working fine for me. Could you please check again?

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/8cda7a93-53d3-4fb8-860f-2f829b43aff2">

**Comment by laurenluz** [comment] 2024-09-25 16:40
@RamRamez I think if the user is actually staking on those chains, they don't see it
![image](https://github.com/user-attachments/assets/e46195d9-ed94-4447-a700-addb67460d77)

**Comment by maryjaf** [comment] 2024-09-29 09:56
![image](https://github.co@RamRamez ser-attachments/assets/b7c9440f-e6e6-46f0-98dc-a61964ff18e5)

@RamRamez

**Comment by RamRamez** [comment] 2024-09-29 16:57
In staging we show zero because the periodFinish fetched from Subgraph is passed. Seems the pool is over.
@aminlatifi Could you please check it?

https://api.studio.thegraph.com/query/76292/giveconomy-staging-gnosischain/version/latest

<img width="863" alt="image" src="https://github.com/user-attachments/assets/b8016405-a7ba-40a9-9eae-c9a74478c012">

**Comment by RamRamez** [comment] 2024-09-29 17:10
@aminlatifi In production, the GIVPOWER will be expired in less than two days in Gnosis and OP.

OP:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/369de801-d11a-4f93-aee9-6558173e3a7f">

Gnosis:
<img width="872" alt="image" src="https://github.com/user-attachments/assets/b6e99612-8f29-4189-9c96-a777cf816ef6">

**Comment by RamRamez** [comment] 2024-09-29 17:24
@aminlatifi on production, no one can stake on OP because the balance fetched from Subgraph for OP is shown as a negative number.

<img width="872" alt="image" src="https://github.com/user-attachments/assets/60a7e9c9-5d3f-4a86-b8f9-0d596816f39c">

**Comment by RamRamez** [comment] 2024-09-29 20:24
@laurenluz About this issue: APR, Claimable and streaming not being shown on all chains
I fixed it and sent the PR. It's waiting for review.

**Comment by RamRamez** [comment] 2024-09-30 14:30
cc @mohammadranjbarz

**Comment by aminlatifi** [comment] 2024-09-30 14:50
> @aminlatifi on production, no one can stake on OP because the balance fetched from Subgraph for OP is shown as a negative number.
> 
> <img alt="image" width="872" src="https://private-user-images.githubusercontent.com/73441857/371874508-60a7e9c9-5d3f-4a86-b8f9-0d596816f39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDc4MTYsIm5iZiI6MTcyNzcwNzUxNiwicGF0aCI6Ii83MzQ0MTg1Ny8zNzE4NzQ1MDgtNjBhN2U5YzktNWQzZi00YTg2LWI4ZjktMGQ1OTY4MTZmMzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE0NDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NTg3OWEzNDJlMWQzYzRiZGRlZDZlYjQ2MzRlZmZkMDZjN2I3NDFmN2E3MGEyMzZlNzNkZGE2YzMyYWNmMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N1RrlTlkVNPkIgU0VCvA_3QfJq-iww3xbRbUbK9FlUM">

I looked at the subgraph, no negative value is there!

**Comment by aminlatifi** [comment] 2024-09-30 14:53
it's the curl value
```
curl --location 'https://api.studio.thegraph.com/query/76292/giveth-giveconomy-optimism/version/latest' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cf_bm=uXcItsNMRkxRH1jzvbUrZviQD3.40RUl5RYlJDkn7ks-1727707418-1.0.1.1-QiKo5r.5oK0WAYDEQ9MDAohaYbks7D7FrvKQ.7sflFrpXJHy8TbXBj5am9N17pH59TIHELZyZbxgZs10Gs80mg' \
--data '{"query":"{\n\n    tokenBalances(where: {token_contains_nocase:\"0x528CDc92eAB044E1E39FE43B9514bfdAB4412B98\"}, orderBy: balance, orderDirection: asc) {\n        token\n        balance\n    }\n}","variables":{}}'
```

**Comment by aminlatifi** [comment] 2024-09-30 14:57
@RamRamez Generally if a round is finished, its APR must be zero and in that case it's correct.
In other cases, there would be an issue with state management or some issue with querying subgraphs.
If you like to be sure, try to directly query the subgraph and parse the result with tools like `jq` and see if it's correct or not.
Also, it has happened that sometimes subgraph resolve incorrect value since its distributed nature and sometimes of nodes is resolving wrong value for a query

**Comment by RamRamez** [comment] 2024-09-30 20:46
@aminlatifi I tried with two different laptops and wallets and can't stake and unstake on OP (production). can you do it?

**Comment by RamRamez** [comment] 2024-09-30 20:51
Because subgraph is returning a negative value for GIV token balance.
<img width="927" alt="image" src="https://github.com/user-attachments/assets/dec27beb-5d4b-45b3-a27f-e8689c21f09e">

**Comment by RamRamez** [comment] 2024-09-30 20:53
> it's the curl value
> 
> ```
> curl --location 'https://api.studio.thegraph.com/query/76292/giveth-giveconomy-optimism/version/latest' \
> --header 'Content-Type: application/json' \
> --header 'Cookie: __cf_bm=uXcItsNMRkxRH1jzvbUrZviQD3.40RUl5RYlJDkn7ks-1727707418-1.0.1.1-QiKo5r.5oK0WAYDEQ9MDAohaYbks7D7FrvKQ.7sflFrpXJHy8TbXBj5am9N17pH59TIHELZyZbxgZs10Gs80mg' \
> --data '{"query":"{\n\n    tokenBalances(where: {token_contains_nocase:\"0x528CDc92eAB044E1E39FE43B9514bfdAB4412B98\"}, orderBy: balance, orderDirection: asc) {\n        token\n        balance\n    }\n}","variables":{}}'
> ```

We use this API for OP:
https://gateway-arbitrum.network.thegraph.com/api/720ca27934ee17d259dc2975d9a6d714/subgraphs/id/zyoJAUh2eGLEbEkBqESDD497qHLGH1YcKH9PBEMnWjM

**Comment by aminlatifi** [comment] 2024-10-01 07:59
> > it's the curl value
> > ```
> > curl --location 'https://api.studio.thegraph.com/query/76292/giveth-giveconomy-optimism/version/latest' \
> > --header 'Content-Type: application/json' \
> > --header 'Cookie: __cf_bm=uXcItsNMRkxRH1jzvbUrZviQD3.40RUl5RYlJDkn7ks-1727707418-1.0.1.1-QiKo5r.5oK0WAYDEQ9MDAohaYbks7D7FrvKQ.7sflFrpXJHy8TbXBj5am9N17pH59TIHELZyZbxgZs10Gs80mg' \
> > --data '{"query":"{\n\n    tokenBalances(where: {token_contains_nocase:\"0x528CDc92eAB044E1E39FE43B9514bfdAB4412B98\"}, orderBy: balance, orderDirection: asc) {\n        token\n        balance\n    }\n}","variables":{}}'
> > ```
> 
> We use this API for OP: https://gateway-arbitrum.network.thegraph.com/api/720ca27934ee17d259dc2975d9a6d714/subgraphs/id/zyoJAUh2eGLEbEkBqESDD497qHLGH1YcKH9PBEMnWjM

It's subgraph studio problem. I ran the query in the optimism-mainnet playground in the studio dashboard, and the result is as follows (ordered by balance ascending):
query: 
```graphql
{

    tokenBalances(where: {token_contains_nocase:"0x528CDc92eAB044E1E39FE43B9514bfdAB4412B98"}, orderBy: balance, orderDirection: asc) {
        token
        balance
    }
}
```
```
{
  "data": {
    "tokenBalances": [
      {
        "token": "0x528cdc92eab044e1e39fe43b9514bfdab4412b98",
        "balance": "0"
      },
      {
        "token": "0x528cdc92eab044e1e39fe43b9514bfdab4412b98",
        "balance": "0"
      },
      {
        "token": "0x528cdc92eab044e1e39fe43b9514bfdab4412b98",
        "balance": "0"
      },
       ...

    ]
  }
}
```

**Comment by aminlatifi** [comment] 2024-10-01 08:00
@RamRamez Can you copy the exact curl from the request in your browser an put here?
When we become sure the problem is on subgraph, we must raise the issue on their sude.

**Comment by RamRamez** [comment] 2024-10-01 10:44
> @RamRamez Can you copy the exact curl from the request in your browser an put here? When we become sure the problem is on subgraph, we must raise the issue on their sude.

@aminlatifi I sent you in DM

**Comment by aminlatifi** [comment] 2024-10-01 12:04
It's strange! subgraph is not working correctly if I don't say we have a bug!
It has not processed transfer events as we expect, even balance changes for that address are not recorded!
I ran this
```
    balanceChanges (where:{account: "0x91ebba819e4bba03065a106290afcb44deb1f9d"})  {
        contractAddress
        account

        amount
    }
```

no balance change is recorded.
I must investigate more

**Comment by aminlatifi** [comment] 2024-10-01 13:38
@RamRamez Can you double check now?!

**Comment by maryjaf** [comment] 2024-10-01 18:36
![image](https://github.com/user-attachments/assets/c71cf46f-e79c-407b-bbf1-35480790cf45)

It seems this issue has been resolved, thanks  @RamRamez 
@laurenluz

**Closed** 2024-10-04 16:06 UTC
Labels: bug, P0
