### ISSUE TITLE
Double Donations??

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4327] opened 2024-06-24 22:41 UTC
Seems like this donation was added to this project twice. I think it was the matching funds from the Galactic Giving QF round:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/aa39f0b3-97b7-479c-b130-2fea6194ed66)

https://giveth.io/project/kokonut-foundation-public-goods-powered-by-trees?tab=donations

It doesn't seem like it is happening for all projects that received matching for that round though. So far, this is the only one I found.

**Comment by WhyldWanderer** [comment] 2024-06-24 22:43
Seems like this is a "Dapp Performance BE" so assigning @CarlosQ96  as he is listed as the Tech Lead for these situations.

**Comment by divine-comedian** [comment] 2024-08-02 19:05
@CarlosQ96 - nudging this one here.

**Comment by divine-comedian** [comment] 2024-08-30 15:06
@CarlosQ96 can we please have an update on this issue

**Comment by divine-comedian** [comment] 2024-11-06 11:22
@CarlosQ96 what is the update on this issue?

**Comment by kkatusic** [comment] 2024-11-06 12:12
> @CarlosQ96 what is the update on this issue?

@divine-comedian, cc @CarlosQ96, I checked this one before:

- double donation exist, only difference that I can find is in hash address of the project, one is with uppercase/lowercase letters other is only with lower case.
- I checked there was only one transaction, it is same txh for both donations, but checked transfers for this project it is one transaction 683.4 ($687.50) Glo Dollar (USDGLO) to project, there aren't two of them.
- Don't know what is procedure for this, to delete one, but which one? Or you add migration for that?
- It is also donations from Donation.eth maybe something failed on Jun 13, 2024 

conclusion is that on token distribution we got error.

**Comment by divine-comedian** [comment] 2024-11-07 07:31
Yep, Carlos needs to delete the extra one from DB

**Comment by CarlosQ96** [comment] 2024-11-07 10:15
Alright Ill delete it right now.

**Comment by CarlosQ96** [comment] 2024-11-07 10:58
@divine-comedian @kkatusic donation deleted. Moving to Done

**Comment by CarlosQ96** [comment] 2024-11-07 11:08
The issue is mostly the ToWalletAddress UpperCase/Lowercase. We have a index to prevent same case, but Solana integration changed the game as CASE is important in solana. 
We can think of a new index that only applies to solana. @divine-comedian  should we create a new issue for this? 

I checked the database are there are no more duplicates.

**Closed** 2024-11-07 11:10 UTC
Labels: bug

**Comment by kkatusic** [comment] 2024-11-07 12:37
Bravo @CarlosQ96
