### ISSUE TITLE
As a Project Owner, I want to add a Solana address to receive donations to

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3393] opened 2023-10-25 17:22 UTC
A Project Owner should be able to simply add a solana address to their project page that defines the recipient address of donations made on Solana 
Should consider any changes in #3078 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/90e94f4b-f29e-491c-ac28-dc1119b7a7cb)

**Comment by MoeNick** [comment] 2023-12-19 14:35
For adding the Addresses on the front end we have 2 views that should work:
- My projects, manage addresses, add address
- Add / Edit project view.

**Comment by aminlatifi** [comment] 2023-12-20 13:31
@RamRamez To add a Solana address to a project note these:
- NetworkId: 0,
- ChainType: SOLANA
- Address capitalization must be preserved

**Comment by RamRamez** [comment] 2023-12-22 11:17
@aminlatifi This error is coming from "walletAddressIsValid" endpoint. I suggest replacing "Eth address" with "Address" to contain Solana addresses as well.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/ddb21902-e988-4c44-8c94-275f577cb684)

**Comment by aminlatifi** [comment] 2023-12-22 12:09
> @aminlatifi This error is coming from "walletAddressIsValid" endpoint. I suggest replacing "Eth address" with "Address" to contain Solana addresses as well.
> 
> ![image](https://private-user-images.githubusercontent.com/73441857/292474528-ddb21902-e988-4c44-8c94-275f577cb684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDcxNzgsIm5iZiI6MTcwMzI0Njg3OCwicGF0aCI6Ii83MzQ0MTg1Ny8yOTI0NzQ1MjgtZGRiMjE5MDItZTk4OC00YzQ0LThjOTQtMjc1ZjU3N2NiNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEyMDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNjg0MDZjNDIwM2E0NDhiNjIyYTlhNDc4MWY5ZDBiNjE2ZGEzMGM5NmU2NTJmMDA2YjI1NzY5OGVkZjc2ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4O7gqEZtjhNyu6l99tQDjh35YCum-J8rM5S6qqtQqG8)

Which mutation are you calling? with which parameters?

**Comment by RamRamez** [comment] 2023-12-23 12:54
> @aminlatifi This error is coming from "walletAddressIsValid" endpoint. I suggest replacing "Eth address" with "Address" to contain Solana addresses as well.
> 
> ![image](https://private-user-images.githubusercontent.com/73441857/292474528-ddb21902-e988-4c44-8c94-275f577cb684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzYwNDAsIm5iZiI6MTcwMzMzNTc0MCwicGF0aCI6Ii83MzQ0MTg1Ny8yOTI0NzQ1MjgtZGRiMjE5MDItZTk4OC00YzQ0LThjOTQtMjc1ZjU3N2NiNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEyNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZTI2NGUwZmQ1MzJmNmMzZTE2NjI2YTgzM2I2MDVlYWNjOWU1ZTY4MmM1NzE1MzgzOGZjYmYzNTAxN2JlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W25iprCkxat7renwx58hu2ewKysYIgYhCgoD5sLQ92o)

I already sent the mutation here. If you call this endpoint and query a wallet address that is already being used for a project, you will see that error.

**Comment by aminlatifi** [comment] 2023-12-24 09:13
> > @aminlatifi This error is coming from "walletAddressIsValid" endpoint. I suggest replacing "Eth address" with "Address" to contain Solana addresses as well.
> > ![image](https://private-user-images.githubusercontent.com/73441857/292474528-ddb21902-e988-4c44-8c94-275f577cb684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMzYwNDAsIm5iZiI6MTcwMzMzNTc0MCwicGF0aCI6Ii83MzQ0MTg1Ny8yOTI0NzQ1MjgtZGRiMjE5MDItZTk4OC00YzQ0LThjOTQtMjc1ZjU3N2NiNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDEyNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZTI2NGUwZmQ1MzJmNmMzZTE2NjI2YTgzM2I2MDVlYWNjOWU1ZTY4MmM1NzE1MzgzOGZjYmYzNTAxN2JlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W25iprCkxat7renwx58hu2ewKysYIgYhCgoD5sLQ92o)
> 
> I already sent the mutation here. If you call this endpoint and query a wallet address that is already being used for a project, you will see that error.

I tested the endpoint with some random address, it works fine
```bash
curl --location 'https://impact-graph.serve.giveth.io/graphql' \
--header 'Content-Type: application/json' \
--data '{"query":"# Write your query or mutation here\nquery {\n  walletAddressIsValid(address:\"2axeaEqsJe9HPrK8QZWD2y9Y3zzdRRQXd9q5qVuuM3Pt\") \n}","variables":{}}'
```

**Comment by MoeNick** [comment] 2023-12-24 12:05
@RamRamez can we make it today?

**Comment by RamRamez** [comment] 2023-12-24 12:17
> @RamRamez can we make it today?

I even worked on it on my weekend (Friday and Saturday) and sent a draft PR.
Adding Solana to create project page is done. I created some projects with Solana address and it's working well.
But we have some typescript problems and some other issues like adding network config.
I'm trying to finalize it today.

**Comment by MoeNick** [comment] 2023-12-24 12:22
Great, Thanks @RamRamez

**Comment by RamRamez** [comment] 2023-12-24 22:15
I can't submit Solana addresses with "updateProjectVerificationForm" endpoint. @aminlatifi Please check it.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/351b2765-36ca-454e-ac0c-111df1803a3a)

**Comment by RamRamez** [comment] 2023-12-24 22:49
I sent the PR.
Create project page, manage funds in verification modal and donations tab in project view, is done.
Tomorrow I will work on Manage addresses in user dashboard (My projects).

**Comment by aminlatifi** [comment] 2023-12-25 08:20
> I can't submit Solana addresses with "updateProjectVerificationForm" endpoint. @aminlatifi Please check it.
> 
> ![image](https://private-user-images.githubusercontent.com/73441857/292690912-351b2765-36ca-454e-ac0c-111df1803a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTEyMjIsIm5iZiI6MTcwMzQ5MDkyMiwicGF0aCI6Ii83MzQ0MTg1Ny8yOTI2OTA5MTItMzUxYjI3NjUtMzZjYS00NTRlLWFjMGMtMTExZGYxODAzYTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA3NTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NDFhYmRhYzY5M2Y3YzEwMzIwMTc2YjI3YmFkOTY5YWRiNTk0ZmZlOTUzMmZhYWUyOWNjNThhMDY5MTY1ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nF4lIjmwWv-OTqhRv1JID9EJFVf814aI-MHM841G-7k)

It will be fixed by https://github.com/Giveth/impact-graph/pull/1210

**Comment by RamRamez** [comment] 2023-12-26 12:41
Adding Solana to managing addresses in My projects in done. I think we need to update backend as well.
When I try to add Solana address with "addRecipientAddressToProject" I get this error.
@aminlatifi can you check please:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/8b95207c-33af-4404-961d-57a9e23f7663)

**Comment by MoeNick** [comment] 2023-12-26 12:47
> Adding Solana to managing addresses in My projects in done. I think we need to update backend as well. When I try to add Solana address with "addRecipientAddressToProject" I get this error. @aminlatifi can you check please: ![image](https://private-user-images.githubusercontent.com/73441857/292869447-8b95207c-33af-4404-961d-57a9e23f7663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTUwNDYsIm5iZiI6MTcwMzU5NDc0NiwicGF0aCI6Ii83MzQ0MTg1Ny8yOTI4Njk0NDctOGI5NTIwN2MtMzNhZi00NDA0LTk2MWQtNTdhOWUyM2Y3NjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEyNDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMGI1YWI4YWFkNjAyZTJhNTgxOWVkZTJmNTg1MTI5ZmY5ZGMzN2Q3ODdhOWIzODQ3OTI0N2JlZmE1YTk0NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.auC4fG7jlDtmq-QsMdNPwc2n5j5Khz7VLBGcrI6u3fQ)

@CarlosQ96 can you take a look, please?

**Comment by MoeNick** [comment] 2023-12-26 12:49
@mohammadranjbarz is on it :))

**Comment by mohammadranjbarz** [comment] 2023-12-26 12:53
@RamRamez  Do you send `chainType` in this query?
I you want to add solana address you should send it `chainType:'SOLANA'`

**Comment by RamRamez** [comment] 2023-12-26 13:04
> @RamRamez Do you send `chainType` in this query? I you want to add solana address you should send it `chainType:'SOLANA'`

Yes, I'm sending it.

**Comment by mohammadranjbarz** [comment] 2023-12-26 13:28
@RamRamez Can you change this line
https://github.com/Giveth/giveth-dapps-v2/blob/2d9e499c25480314e392fbc80521019672cc26df/src/apollo/gql/gqlProjects.ts#L447

and replace `$address: String!`  with `$address: ChainType!`  and test it again?

**Comment by maryjaf** [comment] 2023-12-28 07:45
please take a look on this error in create project page @RamRamez 
<img width="1517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15572858192cb6cc31bfa846dbdd4655261bd403/image.png" alt="image.png" />

**Comment by maryjaf** [comment] 2023-12-28 07:45
please take a look on this error in create project page @RamRamez 
<img width="1517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15572858192cb6cc31bfa846dbdd4655261bd403/image.png" alt="image.png" />

**Comment by maryjaf** [comment] 2023-12-28 08:09
2-
In edit page, when I set an ETH address in solane address, no error message is shown in below modal
and when I tap on publish I get an error 
<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3b2c13088e2e227cddd269dfa56efb228f71fe8/image.png" alt="image.png" />
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11dc20eb7d72f633ea857743e6d461d422bd5d06/image.png" alt="image.png" />

**Comment by maryjaf** [comment] 2023-12-28 08:09
2-
In edit page, when I set an ETH address in solane address, no error message is shown in below modal
and when I tap on publish I get an error 
<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3b2c13088e2e227cddd269dfa56efb228f71fe8/image.png" alt="image.png" />
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11dc20eb7d72f633ea857743e6d461d422bd5d06/image.png" alt="image.png" />

**Comment by maryjaf** [comment] 2023-12-28 14:15
> 1- please take a look on this error in create project page @RamRamez

I haven't seen this error again, maybe it's about my connection

**Comment by RamRamez** [comment] 2023-12-28 14:36
Thanks @maryjaf, I tested these two issues with different browsers and couldn't reproduce the bugs either.

**Comment by maryjaf** [comment] 2024-01-01 10:31
There is an UI issue in showing solana address icon, please check @RamRamez 
<img width="1534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0d06366e07ed991eb4509ddf1baf172083c42ff/image.png" alt="image.png" />
<img width="1610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da863bc0e57eb7790b9279ea83bb012650e7b28f/image.png" alt="image.png" />

**Comment by maryjaf** [comment] 2024-01-01 10:31
There is an UI issue in showing solana address icon, please check @RamRamez 
<img width="1534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0d06366e07ed991eb4509ddf1baf172083c42ff/image.png" alt="image.png" />
<img width="1610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da863bc0e57eb7790b9279ea83bb012650e7b28f/image.png" alt="image.png" />

**Comment by maryjaf** [comment] 2024-01-01 11:00
- [ ] Add solana in create project  page-- Pass
- [ ] Add solana in edit project page -- Pass
- [ ] add solana in manage address modal (my project list) -- Code Review

**Comment by MoeNick** [comment] 2024-01-01 12:14
This issue is still in code review, shall I put it in QA?

**Comment by maryjaf** [comment] 2024-01-01 12:18
> * [x]  Add solana in create project  page-- Pass
> * [x]  Add solana in edit project page -- Pass
> * [ ]  add solana in manage address modal (my project list) -- Code Review

it is the last status

**Comment by MoeNick** [comment] 2024-01-04 06:49
@jainkrati 
You wil talke with team to resolve this problem

**Comment by maryjaf** [comment] 2024-01-08 07:17
> [ ] add solana in manage address modal (my project list) -- Waiting for Code Review

Is this still in code review state?

**Comment by maryjaf** [comment] 2024-01-08 11:56
I'm not sure this bug be related to incomplete  implementation of this part  or not however I describe this to be checked 
when My project has a solana  recipient address, by tapping on manage address and select a chain this address is shown in Eth chain by default 
I think it's better  if a project doesn't have an eth address  the default value of address won't be set
@RamRamez 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8723b3f9-8bac-4fae-ad5c-fc6490c37c8f

**Comment by MoeNick** [comment] 2024-01-08 11:58
Good catch @maryjaf

**Comment by RamRamez** [comment] 2024-01-08 12:35
@maryjaf I've fixed it PR #3533 (without recurring donations enabled)

**Comment by MoeNick** [comment] 2024-01-09 07:43
@maryjaf to QA  add solana in manage address modal (my project list) again please

**Comment by maryjaf** [comment] 2024-01-09 08:03
last changes aren't on stg, maybe it hasn't been reviewed  yet.

**Comment by aminlatifi** [comment] 2024-01-09 09:47
@maryjaf @MoeNick The PR is merged.

**Comment by maryjaf** [comment] 2024-01-09 11:06
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0c4f195a-1dde-4c4d-814a-270e22a36e20

The user has a same address on one or more ETH chain and one address on solana , in this situation by tapping on other eth chain the default address isn't set, is it accepted? @MoeNick 
or current address that it is set on ETH chain should be shown ?

**Comment by MoeNick** [comment] 2024-01-10 08:15
If user has set and eth address before and want to set another eth, we should suggest the same eth address to user. 

This was according to @GriffGreen requirement once and we applied it.
I think @MohammadPCh was implemented that. 

But however if it's too complicated to implement, I think its fine.

**Comment by aminlatifi** [comment] 2024-01-10 08:25
> If user has set and eth address before and want to set another eth, we should suggest the same eth address to user.
> 
> This was according to @GriffGreen requirement once and we applied it. I think @MohammadPCh was implemented that.
> 
> But however if it's too complicated to implement, I think its fine.

@RamRamez has refactored that part. Ramin, can you look at this issue?

**Comment by RamRamez** [comment] 2024-01-11 09:12
In PR #3605, I excluded non EVM chains. So, we won't suggest anything for non EVM chains and will only have address suggestion for ETH addresses

**Comment by MoeNick** [comment] 2024-01-11 09:14
> 
> 
> https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0c4f195a-1dde-4c4d-814a-270e22a36e20
> 
> 
> 
> The user has a same address on one or more ETH chain and one address on solana , in this situation by tapping on other eth chain the default address isn't set, is it accepted? @MoeNick 
> 
> or current address that it is set on ETH chain should be shown ?

@RamRamez do in this case, user get done suggestions for eth addresses?

**Comment by RamRamez** [comment] 2024-01-11 09:17
@MoeNick Yes, we should suggest

**Comment by maryjaf** [comment] 2024-01-11 09:58
Plz check this @RamRamez 
when my user has a solana address and one address on eth chain, the default address won't be  set correctly for other eth chains and solana address be shown

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ecf13f32-1ef3-4fd5-9ced-67f7d4a458b4

**Comment by maryjaf** [comment] 2024-01-11 11:45
> when my user has a solana address and one address on eth chain, the default address won't be set correctly for other eth chains and solana address be shown

Thanks @RamRamez this problem has been resolved

**Closed** 2024-01-28 15:08 UTC
Labels: Solana
