### ISSUE TITLE
GIV token holdings in navbar is showing different number periodically

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4407] opened 2024-07-11 17:37 UTC
Ubuntu 22.04
Metamask
Brave

On the homepage while connected to Giveth the navbar element which shows my GIV token holdings is occasionally switching to show a different number, it will show the same holdings for about 10-15 seconds then switch to show a different number for about 10-15 seconds, then it will switch back to show the 1st number - it repeats this behaviour infinitely.. 

could this be related to fetching my GIV token balance between gnosis chain and optimism?

The expected behaviour, I think is that it shows just my GIV holdings on the chain I'm connected to.. but @laurenluz would be able to know decisively. 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/731f1c01-2114-45af-8642-fc07166f0767

**Comment by laurenluz** [comment] 2024-07-17 13:46
oh that's weird. imo - it should just show your GIV holdings on the corresponding chain. I remember Griff saying that we should show the sum of GIV accross chains, but tbh I think it's overcomplicating things...

@mohammadranjbarz can you investigate or assign the appropriate person to fix this?

**Comment by Danibelle** [comment] 2024-07-23 00:03
Here's a screen capture from today after some GIVbacks came out..  happening on Optimism only for me, but I'll check Gnosis now and see what the numbers are for any correlation as suggested previously by Mitch.

https://www.loom.com/share/6f517fa0570a4cb29a25f2bb81dc4b52?sid=3539504c-b3a4-4d68-adb9-7386dcdeae8d

**Comment by Danibelle** [comment] 2024-07-23 00:13
Follow up.. after staking, the difference keeps popping back in..

https://www.loom.com/share/30ce1f1d997b4ce2a178056a1349c849?sid=61c76e4d-e699-4bd6-9f18-e768737fb0ef

**Comment by laurenluz** [comment] 2024-07-24 08:54
@aminlatifi maybe you have time to look into this?

**Comment by aminlatifi** [comment] 2024-07-24 10:09
> @aminlatifi maybe you have time to look into this?

Sure, like to know @MohammadPCh opinion on this first, because the related modules will undergo a refactoring soon.

**Comment by MohammadPCh** [comment] 2024-07-24 13:14
@divine-comedian It only happens on production, am I right?

**Comment by divine-comedian** [comment] 2024-07-24 14:25
> @divine-comedian It only happens on production, am I right?

yes.

**Comment by laurenluz** [comment] 2024-07-31 12:18
just a bump on this @MohammadPCh

**Comment by MohammadPCh** [comment] 2024-08-02 13:26
@divine-comedian @laurenluz, this issue is related to the subgraph service. It returns different values with each request:
For instance, sometimes it returns this:
<img width="414" alt="Screenshot 2024-08-02 at 4 52 47 PM" src="https://github.com/user-attachments/assets/e2114fa9-b3e1-414d-bcaa-ce99f6c31f22">
And on the next request, it returns this:
<img width="414" alt="Screenshot 2024-08-02 at 4 53 39 PM" src="https://github.com/user-attachments/assets/0c76872e-9415-4014-971f-7cbcc401df55">
We need to investigate this issue with our subgraph service.
@geleeroyale, could there be any caching or something on our server that might be causing this problem?
@aminlatifi wdyt?

**Comment by geleeroyale** [comment] 2024-08-03 12:51
@CarlosQ96 You implemented some caching, right? Could it be related?

**Comment by divine-comedian** [comment] 2024-08-04 15:06
Hey guys! I tested this again on production and this error no longer appears :thinking: perhaps another release has fixed this issue - Let's see if @Danibelle also notices if it's been corrected.

**Comment by aminlatifi** [comment] 2024-08-06 07:13
We found the root cause... it was an issue with the optimism subgraph. It occasionally returns an obsolete response. 
The issue has been reported and they are working on that https://discord.com/channels/438038660412342282/870386963562258433/1270085150394548334

**Comment by laurenluz** [comment] 2024-08-06 17:52
will you update us @aminlatifi once they resolve it so it can be tested? or we should QA now?

**Comment by aminlatifi** [comment] 2024-08-06 20:18
> will you update us @aminlatifi once they resolve it so it can be tested? or we should QA now?

They say it's fixed. I couldn't reproduce the error too.

**Comment by laurenluz** [comment] 2024-08-06 21:55
epic! @maryjaf can you do a quick test & check too? if it looks ok, I think we can jsut close this

**Comment by maryjaf** [comment] 2024-08-07 06:36
I've tested on Gnosis and OP on production, it looks good and there is no problem.

**Closed by maryjaf** 2024-08-07 06:36 UTC
Labels: bug, GIVeconomy
