### ISSUE TITLE
Public view | GIVpower tab

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2563] opened 2023-04-23 12:57 UTC
The GIVpower content is 100% now. And the current/projected rank is on the side instead of on top.

### Design resource
[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=131-61364&t=PufNboTMnlqsdv5i-4)

![Screenshot 2023-05-01 at 4.37.05 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/7aa163af-a290-424c-a543-b315e5f9eaeb)

**Comment by maryjaf** [comment] 2023-05-18 07:58
The number of give powers of this project (https://givproject.vercel.app/project/how-many-photos-is-too-many-photos?tab=givpower)is 10, which is displayed in page 1
However, it has pagination and page 2 is also displayed @MohammadPCh 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6422f746-bb7d-4bd6-8c3a-bf716780f473)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8f0c782f-73a6-433f-86a5-bf879994d0da)

**Comment by maryjaf** [comment] 2023-05-18 08:01
This section isn't shown now![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/db41934d-5cba-4343-a1b3-47f96db91a90)
Is this removed from this page? @MohammadPCh

**Comment by MoeNick** [comment] 2023-05-22 10:06
Viva @maryjaf ! <:3

**Comment by maryjaf** [comment] 2023-06-06 15:44
> The number of give powers of this project (https://givproject.vercel.app/project/how-many-photos-is-too-many-photos?tab=givpower)is 10, which is displayed in page 1 However, it has pagination and page 2 is also displayed @MohammadPCh ![image.png](https://camo.githubusercontent.com/8089c68edc76cb4286d0858d07621dfafcfb5bcf1a8cdbc82e93a0f33235b3e5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f36343232663734362d626237642d346264362d386333612d626637313637383066343733) ![image.png](https://camo.githubusercontent.com/794248bb345da4f19b69435b6bc5cef975702fe8fa728f0bbe54b7a053bc7275/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38663063373832662d373361362d343333662d383661352d626638373939393464306461)

This problem isn't fixed, plz check  @MohammadPCh

**Comment by MohammadPCh** [comment] 2023-06-11 06:48
@maryjaf  Thanks, for taking care of everything.
the pagination issue is fixed now, the problem is that the user that his balance is zero.
and about the boost button, it has a different issue. so let's skip it here

**Comment by MoeNick** [comment] 2023-07-06 10:29
Can @maryjaf start testing?

**Closed** 2023-07-31 09:38 UTC
