### ISSUE TITLE
[BUG][STG] There is a problem related to Solana (NetworkId= 0)

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4368] opened 2024-07-03 10:48 UTC
**Describe the bug**
The network Id related to Solana is set 0 on stg and production
but on stg when the user tries to donate on solana chanin, an error happens and this bug doesn't exist on production

**To Reproduce**
1. The network is set on solana
2. Go to a project with solana address 'https://staging.giveth.io/donate/testamotestam01'
3. Click on 'Donate'

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7011f669-b5e1-4e49-843e-3ba514f014e3

cc: @MohammadPCh

**Comment by divine-comedian** [comment] 2024-07-07 14:24
@maryjaf is this related to or the same issue as #4371 ?

**Comment by ae2079** [comment] 2024-07-19 00:59
@maryjaf 
I tried to reproduce this bug, but the project you mentioned (https://staging.giveth.io/donate/testamotestam01) does not support the Solana network, and I tried another project that supports the Solana network (https://staging.giveth.io/project/a-delicious-help) and I successfully donated to that without any problem. (https://staging.giveth.io/project/a-delicious-help)

**Comment by divine-comedian** [comment] 2024-07-19 13:49
Also couldn't repro this error while donating to another project on solana devnet - closing for now..

**Comment by maryjaf** [comment] 2024-07-21 06:39
- [ ] Based on above step I could reproduce this problem again 
this issue was raised by @MohammadPCh and for him this bug also happened
and this problem happened for us only on staging not production 
@ae2079 @divine-comedian 

https://github.com/user-attachments/assets/99fb41f9-abe4-4208-b923-9d9f7d4d5006

**Comment by ae2079** [comment] 2024-07-21 10:45
> * [ ]  Based on above step I could reproduce this problem again
>   this issue was raised by @MohammadPCh and for him this bug also happened
>   and this problem happened for us only on staging not production
>   @ae2079 @divine-comedian
> 
>  Screen.Recording.2024-07-21.at.10.06.34.AM.mov
Looks like it is related to project creation flow, not the solana network, because the issue is with some specific projects, so I'll check the flow and project and get back to you

**Comment by maryjaf** [comment] 2024-07-21 11:06
By this release this bug also happens on production

-The project supports solana
-But when my network is set on solana 
-I see switch network modal and solana isn't shown in this modal 


https://github.com/user-attachments/assets/2cb16b6f-4b75-4c54-8b94-3061641df76a

**Comment by MohammadPCh** [comment] 2024-07-21 12:57
@maryjaf It appears that there are no Solana-related tokens; all the tokens are for EVM chains.

**Comment by MohammadPCh** [comment] 2024-07-21 13:18
@mohammadranjbarz

**Comment by ae2079** [comment] 2024-07-21 14:03
The bug is related to the network ID of Solona addresses in the DB, I checked it and 2 Solana addresses in the staging had 0 value for their network ID and I set them to 103 (Solana Devnet) and now, the bug is fixed and I had donated to this project successfully on Solana network: https://staging.giveth.io/project/testamotestam01?tab=donations
@maryjaf @divine-comedian Now, I think we can consider as resolved

**Comment by divine-comedian** [comment] 2024-07-21 15:08
OK - and now this bug is on production? We should do the required testing and prepare a hotfix.

**Comment by ae2079** [comment] 2024-07-21 19:26
> OK - and now this bug is on production? We should do the required testing and prepare a hotfix.

no, @mohammadranjbarz  fixed the data manually, and now everything is OK

**Comment by maryjaf** [comment] 2024-07-21 20:16
This bug has been fixed on production

**Closed** 2024-07-22 13:54 UTC
Labels: bug
