### ISSUE TITLE
Donating USDC on Optimism for Giveth QF

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-dapps-v2#3355] opened 2023-10-16 10:07 UTC
**Describe the bug**
I had $44 worth of USDC on OP and 1) it would not populate and show that I had any in Giveth platform, even though it would show in my MetaMask Wallet. Then 2) when I tried to donate it would say I didn't have enough funds 

**To Reproduce**
1. Go to any OP QF round project and try to donate USDC on OP chain

**Expected behavior**
I expected to be able to use my $44 worth of USDC on OP to donate to the OP QF round on Giveth's platform 

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/106797533/5431e608-c857-4989-8b2d-9d827ee6e78a)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/106797533/5b30d660-ca69-4d8e-9af1-e704439e28d7)

**Desktop (please complete the following information):**
 - Browser: Google Chrome
 - Version: windows 11 version 22h2

**Additional context**

**Comment by MoeNick** [comment] 2023-10-17 07:07
@MohammadPCh I guess we solved this issue, is it back again ?

**Comment by maryjaf** [comment] 2023-10-17 08:37
USDC is shown 0 for me @MohammadPCh 
<img width="1389" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c4cfd512-5bb7-4d87-ae16-9e7505d0c5c9">

**Comment by MohammadPCh** [comment] 2023-11-01 11:06
@divine-comedian @mohammadranjbarz
We did some investigation with @maryjaf on this issue:
we use this USDC address on our backend for operations:
`0x7F5c764cBc14f9669B88837ca1490cCa17c31607`
but I think the main USDC address is this:
`0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85`
The problem is that @maryjaf has some balances on `0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85` but we checked the user's balance on` 0x7F5c764cBc14f9669B88837ca1490cCa17c31607`.
Who should decide about it? I think we need to change it to `0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85` in the backend.

**Comment by divine-comedian** [comment] 2023-11-01 11:27
I think both are valid unfortunately

I remember now that it was an issue with USDC bridging 

The token was bridged first with the Optimism bridge, that is the one in our db

While Circle made their own native USDC bridge which became the one we are missing

Both are widely used versions of USDC.

However the one currently in our DB should have a symbol of USDC.e to match what is shown on block explorers
https://optimistic.etherscan.io/token/0x7F5c764cBc14f9669B88837ca1490cCa17c31607

**Comment by MohammadPCh** [comment] 2023-11-01 11:35
@divine-comedian Thanks, who can fix it in the admin dashboard?

**Comment by divine-comedian** [comment] 2023-11-01 15:06
Either @mohammadranjbarz @WhyldWanderer or myself - However I will be back to work on Friday

**Comment by WhyldWanderer** [comment] 2023-11-01 18:18
I changed the symbol of 0x7f5c764cbc14f9669b88837ca1490cca17c31607 to USDC.e.

Can you confirm the change?
The token does not show up in the dropdown menu for me on the DApp even though I have a balance.
I had to copy/paste the address in order to donate with that token.

Is that the expected outcome?

**Comment by maryjaf** [comment] 2023-11-02 07:38
Now I see the below pic 

<img width="1423" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8df9b240-87e7-4e58-ab15-c68b3da7f57f">

and I couldn't see the balance of this token in dApp :
Token Details
0.14972
$0.15 USD
Token contract address
0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85
Token decimal:
6
Network:
Optimism

**Comment by divine-comedian** [comment] 2023-11-03 13:33
The issue is that while we changed the symbol to USDC.e the other USDC token that was missing completetly wasn't added in the admin JS 

I added it now and should show up correctly on production @maryjaf

**Comment by MohammadPCh** [comment] 2023-11-06 06:41
@divine-comedian does it have a different Icon? what is its icon?

**Comment by divine-comedian** [comment] 2023-11-06 14:04
No it's the same

**Comment by maryjaf** [comment] 2023-11-08 12:54
The issue related to showing 0 balance has been resolved, only thing remains is changing the icon of USDC.e @MohammadPCh 
<img width="1354" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6480155a-ca4a-472e-96ee-4d86187cc72a">

**Comment by divine-comedian** [comment] 2023-11-08 13:29
the image should be resolved in merge #3416

**Closed** 2024-01-02 22:53 UTC
Labels: bug
