### ISSUE TITLE
Why am I forced to switch to polygon when connecting a new wallet? (bug fix)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4377] opened 2024-07-03 16:04 UTC
I tried connecting my metamask to Giveth with my wallet on gnosis chain. to connect, I had to sign a message... but then it was trying to make me switch to polygon... I rejected the network switch... but then it said the connect wallet failed.

It basically didn't allow me to connect my wallet until I allowed giveth to switch the network... and then I could switch back to gnosis to actually make the donation.

Weird bug.

@divine-comedian who is the right person to address this?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/27c96684-a966-45b2-ab15-3cd63c4b9b92)

**Comment by divine-comedian** [comment] 2024-07-03 17:24
I tested this out a bit more and was able to reproduce this issue, in order to repro:

1. Sign into Giveth with Ethereum on any given network that we support 
2. Sign out on Giveth, switch network on metamask
3. Sign into Giveth again
4. See prompt from MM for you to switch network (this is the bug) 

**The expected behaviour is that if you connect to giveth from any network we support you are not prompted to switch to a specific network**, unless on some certain conditions - such as the donate page to switch network when a project doesn't accept donations from your currently connected network. 

As a side note, some users might be getting signed out automatically because of this other bug related to QF page #4379

**Comment by laurenluz** [comment] 2024-07-03 17:29
Thanks @divine-comedian! so much more clear <3

**Comment by divine-comedian** [comment] 2024-07-10 13:55
@mateodaza  says it is related to #4401 and could be solved when the PR is merged

**Comment by maryjaf** [comment] 2024-07-11 11:52
> * Sign into Giveth with Ethereum on any given network that we support
> * Sign out on Giveth, switch network on metamask
> * Sign into Giveth again
> * See prompt from MM for you to switch network (this is the bug)

Based on these steps I couldn't reproduce it 
Did I follow the steps correctly? @divine-comedian 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2f20c10c-858c-4a22-9adc-506f5fd71262

**Comment by divine-comedian** [comment] 2024-07-22 14:39
@mateodaza  - please take a look at this

**Comment by mateodaza** [comment] 2024-07-23 01:17
@divine-comedian @laurenluz @maryjaf  I looked everywhere to find a configuration but seems like the default behavior goes like...
- if you previously had a session it will default to that specific network
- it will ask for a network before picking a wallet if it's your first time ever

The solution I suggest is to forcing to always ask for a network before picking the wallet on the first sign-ups, showing this modal initially
![image](https://github.com/user-attachments/assets/4cbc8702-49bd-4bd1-86cf-b780f65be630)

Is this good enough? I have a branch set with this config here so you can check it out [here](https://giveth-dapps-v2-oz6jf4n8w-givethio.vercel.app/es?vercelToolbarCode=4WU0eiXpD8aPflm)

ps: can't find on the docs to support what I'm saying but I think it's a feature and not a bug from web3modal to be "smart enough" and always go back to your last session, tried this with other connectors and the behavior is different, anyway they do have a config to always default a chain but we're multi-chain so it doesn't help us

**Comment by divine-comedian** [comment] 2024-07-23 15:53
@mateodaza thanks! I tested it out and I think it's okay... one more change while you're in there... 

from the navbar when a user clicks "Switch Network" we should also show the same "choose network" view like the one you've shown above 

here's a short video showing the current flow, from your feature branch: 

https://github.com/user-attachments/assets/1e04bd77-fdb9-4f8b-baaa-69db416998b3

**Closed** 2024-08-30 14:26 UTC
Labels: bug, P0
