### ISSUE TITLE
Incorrect wallet address in GIVbacks email

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#1660] opened 2022-10-17 09:58 UTC
Pasting copy of email query
"I'm getting emails that say: 
Your Round 19 GIVbacks have been distributed and are ready to claim! Thank you for participating in the GIVeconomy and for making the world a better place for all! All GIVers that donated $10 or more cumulatively to any verified projects during Round 19 are also eligible to claim a POAP! (connect your address 0xad7575aefd4d64520c3269fd24eae1b0e13dbe7b to claim) 
...but I don't own/recognise the address 0xad7575aefd4d64520c3269fd24eae1b0e13dbe7b"

**Comment by clara-zi** [comment] 2022-10-17 10:02
Checked in etherscan - address appears to belong to a project owner with a portfolio of 2 projects on platform, however address is not used for either project.
To check:
1) is set-up for mail merge correct in AutoPilot?
2) is there a any connection between this wallet address and the person emailed.

**Comment by MoeNick** [comment] 2022-10-17 10:21
I mention you here cause you are our autopilot and support hero. @CarlosQ96

**Comment by CarlosQ96** [comment] 2022-10-26 04:09
@clara-zi I need a bit more details, what project/user-address are the correct ones that received donations on giveth? to investigate further.

I looked up in the database the address 0xad7575aefd4d64520c3269fd24eae1b0e13dbe7b it has an empty user created (no email, no info) which is weird. 
But at the same time I found no projects with said address or any project related to this user.

My suspicion is a certain piece of data overlapped that later was changed, most likely the address (in uppercase), as I see this user is quite old.

I need more info to investigate better, the connection between the wallet and the person that mailed.

Regarding autopilot, I am not sure how givbacks emails are sent atm. I'll ask @divine-comedian or @WhyldWanderer

**Comment by divine-comedian** [comment] 2022-10-26 13:37
also noticing issues with https://github.com/Giveth/giveth-planning/issues/976#issuecomment-1290314132 that seems to be related with autopilot or potentially segment sending wrong information

**Comment by ahmadabugosh** [comment] 2022-11-03 10:51
Hey team, I have an update on [this issue](https://github.com/Giveth/giveth-planning/issues/976)

**Comment by CarlosQ96** [comment] 2023-02-20 14:18
sent a list to @ahmadabugosh and @WhyldWanderer regarding all users that have donated so we can check any difference.

**Comment by MoeNick** [comment] 2023-02-27 09:49
Is there any update @CarlosQ96 ?

**Comment by CarlosQ96** [comment] 2023-04-10 13:46
@ahmadabugosh has this issue ocurred again after I passed you the CSV? 

I have not found the root cause, but want to know.

**Comment by ahmadabugosh** [comment] 2023-04-16 23:11
Hey @CarlosQ96 , here are a few more I noticed that were wrong in GIVbacks round 33. I mentioned what the email should be and what they showed up as in Autopilot. I already fixed them so I could send the GIVbacks email, but I still don't know what the cause is: https://docs.google.com/spreadsheets/d/1nXT83E__MHY3Lj8wpXNmOyZ4z60KARykrR3e6rqwnlg/edit#gid=0

**Comment by CarlosQ96** [comment] 2023-04-18 04:08
Thankss @ahmadabugosh ill be checking this cases to find the issue

**Comment by ahmadabugosh** [comment] 2023-04-26 06:52
@CarlosQ96 I just added the ones I noticed were wrong in GIVbacks round 34 in Autopilot as well: https://docs.google.com/spreadsheets/d/1nXT83E__MHY3Lj8wpXNmOyZ4z60KARykrR3e6rqwnlg/edit#gid=267683724

**Comment by ahmadabugosh** [comment] 2023-05-10 12:31
Hey @CarlosQ96 There were 3 wrong ones in this round too: https://docs.google.com/spreadsheets/d/1nXT83E__MHY3Lj8wpXNmOyZ4z60KARykrR3e6rqwnlg/edit#gid=107192263

Did you get a chance to investigate?

**Comment by laurenluz** [comment] 2023-06-12 15:32
has this been fixed yet? @CarlosQ96 ?

**Comment by divine-comedian** [comment] 2023-07-19 14:33
We will need to manually check each call to the notification center, data sent to the wrong place 

Need to check each email flow and each flow in autopilot

**Comment by MoeNick** [comment] 2023-08-16 13:25
@divine-comedian do yu want to move Segments autopilot issues to be resolved in DApp WG? if so, we need to onboard a person. if not, we can move it to planning repo for comms.

**Comment by divine-comedian** [comment] 2023-08-17 19:31
> @divine-comedian do yu want Segments autopilot issues to be resolved in DApp WG? if so, we need to onboard a person. if not, we can move it to planning repo for comms.

Yup let's deal with it in dApp! As we chatted about then maybe @RamRamez @CarlosQ96 and @ahmadabugosh can work on these issues?

**Comment by MoeNick** [comment] 2024-02-06 11:18
Can I put it inside Ortto Migration? if not, how do we want to deal with it? P1? @divine-comedian

**Comment by ahmadabugosh** [comment] 2024-02-06 11:34
@MoeNick I think the Ortto migration should fix it, because we would no longer be relying on the Segment event (which I think was causing this issue in the first place)

**Comment by MoeNick** [comment] 2024-02-06 12:59
OK I put it inside ortto epic to test the validity of GIVbacks email later.

**Comment by MoeNick** [comment] 2024-03-03 16:50
@RamRamez @divine-comedian 
Did we implement the GIVbacks emails as well?
SHall I put it in UAT?

**Comment by RamRamez** [comment] 2024-03-04 07:23
@MoeNick It's easy to implement but it wasn't part of the email migration epic, so we don't have it right now.
We only add GIVbacks round tag for each user donated on that round.

**Comment by divine-comedian** [comment] 2024-03-04 13:11
No @MoeNick - the GIVbacks email is handled manually by @WhyldWanderer when the round analysis is finished, which can be an arbitrary time - it is not something triggered by our app

**Closed** 2024-03-14 19:56 UTC
Labels: bug
