### ISSUE TITLE
GIVpower | My Account - Boosted Projects-  Manage GivPower

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#758] opened 2022-05-19 12:13 UTC
- Edit boosting -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A236357)

- Edit boosting (amounts changed) -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A238961)

- update boosting confirmation modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13185%3A240957)

- Removing a boost modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12771%3A233321)

- Removing the last boosted project error modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12771%3A233434)

**Edge cases**
- only 3 boost and locking -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13029%3A251757)
- exceeding 100% -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13046%3A253456)

## Guides 

- Responsive guides -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12921%3A236174)

- Mobile design -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12921%3A236339)

**Comment by MoeNick** [comment] 2022-09-12 14:23
@divine-comedian @maryjaf pls confirm and merge.

**Comment by maryjaf** [comment] 2022-09-15 17:31
I didn't see this modal when i applied some change in boosting percentage

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/a9a18e69-8233-4817-814a-55ff1c0471e3)

**Comment by MohammadPCh** [comment] 2022-09-18 08:32
@maryjaf Thanks for reminding me. I will leave a PR for it today.

**Comment by MohammadPCh** [comment] 2022-09-18 08:52
@divine-comedian Thanks for testing and fixing.
About the black line, It's weird can you take a video when it happens? because I can't reproduce it.
it's easy to show the total GIVpower at the bottom but we don't have it on the design. also, we show it on top of the table.
Thanks again.

**Comment by MohammadPCh** [comment] 2022-09-19 12:39
@maryjaf the save modal merged. now you can test it. thanks.

**Comment by maryjaf** [comment] 2022-09-19 17:51
> @maryjaf the save modal merged. now you can test it. thanks.

With the new change, the modal is now displayed
But despite selecting the "cancel ", the changes will be applied

**Comment by divine-comedian** [comment] 2022-09-19 19:27
> @divine-comedian Thanks for testing and fixing. About the black line, It's weird can you take a video when it happens? because I can't reproduce it. it's easy to show the total GIVpower at the bottom but we don't have it on the design. also, we show it on top of the table. Thanks again.

it might be a firefox issue - check out this quick video
[Screencast from 19-09-22 14:25:45.webm](https://user-images.githubusercontent.com/67759413/191099344-055fd157-e84a-400c-b2da-9acffd8256e9.webm)

**Comment by MohammadPCh** [comment] 2022-09-21 11:26
@divine-comedian may be it is scroll. because your icons do not show correctly, do yo see the screen in 100% zoom?

**Comment by maryjaf** [comment] 2022-09-21 12:32
> @maryjaf the save modal merged. now you can test it. thanks.

Thanks @MohammadPCh it's ok .

**Comment by MohammadPCh** [comment] 2022-09-21 14:03
@divine-comedian can you test it on this preview link?
https://giveth-dapps-v2-git-758-fix-boost-table-icon-givethio.vercel.app/

**Comment by divine-comedian** [comment] 2022-09-21 14:13
looks good now! 

![image](https://user-images.githubusercontent.com/67759413/191527970-c951d848-d7b6-4233-a2ff-5cd5d6273303.png)

**Comment by maryjaf** [comment] 2022-09-22 09:14
Can we move this issue to the unit test pass column? @divine-comedian

**Comment by maryjaf** [comment] 2022-09-29 08:36
plz check this scenario @MohammadPCh 
I have 1 project in boosting project tab with 100% of my giv power
When I select the EDIT BOOSTING option and change it from 100 to 50
And then tap on SAVE CHANGES
It is better to display a message to the user that this change is not possible

**Comment by MohammadPCh** [comment] 2022-10-04 10:08
@maryjaf Thanks for reporting this, I disabled the edit boosting button if the user only has one boost. but I think it's better to have a design for this scenario or at least have confirmation for it from @mosaeedi

**Comment by maryjaf** [comment] 2022-10-04 11:20
> @maryjaf Thanks for reporting this, I disabled the edit boosting button if the user only has one boost. but I think it's better to have a design for this scenario or at least have confirmation for it from @mosaeedi

Is this change on givpower branch? 
I tested again but i didn't see changes

**Comment by maryjaf** [comment] 2022-10-04 12:08
> @maryjaf Thanks for reporting this, I disabled the edit boosting button if the user only has one boost. but I think it's better to have a design for this scenario or at least have confirmation for it from @mosaeedi

I tested and disabled the edit boosting button if the user only has one boost.
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/41988a79-1507-4ceb-a568-1af069fee419)disabled the edit boosting button if the user only has one boost.
I also agree that a different design should be considered for this case

**Comment by MohammadPCh** [comment] 2022-10-04 13:53
@MoeNick what do you think?

**Comment by MoeNick** [comment] 2022-10-09 08:56
I agree with this UX for now.

**Comment by laurenluz** [comment] 2022-10-24 22:14
Just looking through these issues, I also agree w/ this. let's not make any more changes here until after we launch

**Comment by maryjaf** [comment] 2022-10-31 16:48
. only 3 boost and locking -> Figma link
I don't see this message according to the figma link given in the description:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/40a9af53-1c98-42d3-9756-3a19d1199f72)I don't see this message according to the figma link given in the description
plz check @MohammadPCh

**Comment by laurenluz** [comment] 2022-10-31 20:29
![image](https://user-images.githubusercontent.com/75490971/199104283-cde66197-d024-45e1-836b-c456cbf7ba79.png)

**Comment by RamRamez** [comment] 2022-11-08 15:53
> @MohammadPCh - the copy is really not good on this tooltip... if you are implementing this, please have it say:
> 
> "You can't lock every percentage because the total must equal 100%."
> 
> I changed this in the figma as well.
> 
> ![image](https://user-images.githubusercontent.com/75490971/199104490-c2d68caf-48a3-482a-b4f8-a289a18a7bd7.png)

Maybe the word `be` is missed in that sentence.
"You can't lock every percentage because the total must **be** equal 100%."
@laurenluz definitely you know better than me.

**Comment by laurenluz** [comment] 2022-11-08 18:53
@RamRamez thanks for keeping an eye out! this is a funny nuance though.. that sentence was actually ok before. it can either be:

"You can't lock every percentage because the total must equal 100%."

or

"You can't lock every percentage because the total must be equal to 100%."

I am happy to make it option 2 if that sounds better universally - your call.

**Comment by maryjaf** [comment] 2022-11-10 15:56
Now this message is shown "You can't lock every percentage because the total must equal 100%." and it passed
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7ad03cb5-93cd-40c3-a5bb-4c3cf082606c)

**Closed** 2022-12-12 19:48 UTC
Labels: GIVeconomy, GIVPower
