### ISSUE TITLE
Success donation page 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3697] opened 2024-01-31 08:08 UTC
By changes related to Super Fluid, donation success page has been changed and I think it should be fixed 

current view on stg :

<img width="1436" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ffb2f6e2-71a1-4525-a187-0ce1c13322b8">

previous view:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a89b5b4c-da5f-46f4-a3b5-8882f69de4e1)

cc: @MohammadPCh @alireza-sharifpour @MoeNick

**Comment by MoeNick** [comment] 2024-01-31 10:02
@jainkrati fyi to assign. 

with feature flags of SOL and Superfluid ON in staging some functionalities like this issue and https://github.com/Giveth/giveth-dapps-v2/issues/3694#issuecomment-1916970112 are malfunctioning on staging which needs time to resolve. 

I will put P1 for this as it may block proper testing.

**Comment by jainkrati** [comment] 2024-02-02 08:12
@MohammadPCh have you worked on this in the past?

**Comment by MohammadPCh** [comment] 2024-02-06 18:35
@maryjaf, just to clarify, what you're seeing is not a bug. The recurring donation feature flag is currently active on staging, so this behavior is expected.

**Comment by maryjaf** [comment] 2024-02-06 18:39
So it means that new design is final and approved ?

**Comment by MohammadPCh** [comment] 2024-02-06 18:53
In light of the conversation with @maryjaf, we can close this issue. The old design will persist on production until the flag for it is turned off.

**Closed by MohammadPCh** 2024-02-06 18:53 UTC
Labels: bug, SuperFluid, P1
