### ISSUE TITLE
GIVpower - missing tooltips on APR & "unstake" on the farm card

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1312] opened 2022-08-04 17:36 UTC
@MohammadPCh 

We want to have a "?" next to "APR" on the GIVpower card... and we want the content of the tooltip to change based on whether or not the user is staking GIV.

If not staked/connected "This is the range of possible APRs for staked and locked GIV. Lock your GIV for longer to earn greater rewards."
If staked "This is the weighted average APR for your staked (and locked) GIV. The full range of APRs for staking and/or locking is 100%-1000%. Lock your GIV for longer to earn greater rewards."

Note! the range of APRs in the tooltip "if staked" should be the actual, dynamic range.

Please see the [figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10527%3A195497):

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/18975663-7a05-48a1-8948-b42f5f406b08)

**Comment by divine-comedian** [comment] 2022-08-11 16:32
Are we testing this on https://givpower.vercel.app/ ?

**Comment by clara-zi** [comment] 2022-08-12 15:15
Tested staked version in: https://givpower.vercel.app/givfarm

1) Tested and confirmed " ? " added next to APR and tooltip is activated with mouse hover.

2) Text matches figma example, except for dynamic range (see point 3).

3) Tested and confirmed text includes actual dynamic range specific to my GIVpower, in this case: 451.44% - 2347.5% (not "100%-1000%" as in text sample).

"This is the weighted average APR for your staked (and locked) GIV. The full range of APRs for staking and/or locking is 100%-1000%. Lock your GIV for longer to earn greater rewards." 

Does the APR range seem reasonable @laurenluz @aminlatifi @MohammadPCh


<img width="230" alt="image" src="https://user-images.githubusercontent.com/100724132/184382819-72f00cd2-0197-40be-a8ba-d77fd18724f4.png">

**Comment by clara-zi** [comment] 2022-08-12 15:21
Continuing with same staked example test:

I see a "?" to the right of my APR % , which is not on the figma design:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/100724132/184386134-93912a54-4a7d-4cfb-a775-56cac400bfea.png">

this is activated with a mouse-click, showing text in screenshot below: 

<img width="193" alt="image" src="https://user-images.githubusercontent.com/100724132/184386911-995f4f1a-9ffa-45dc-9736-ae288e4a2919.png">

**Comment by clara-zi** [comment] 2022-08-12 15:25
Figma shows tooltip (" ? ") next to GIV under 'unstake'  this has not yet been added to Farm Card:

<img width="199" alt="image" src="https://user-images.githubusercontent.com/100724132/184387542-c98724d5-1cec-4451-bf21-dd9d37a7b26d.png">

**Comment by clara-zi** [comment] 2022-08-12 15:33
UNSTAKED version:
1) Tested and confirm Tooltip is present and activated next to APR. Text is correct and matches Figma design:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/100724132/184389179-d6a37493-e5b9-49b5-9a69-2050d24a04d6.png">

**Comment by laurenluz** [comment] 2022-08-12 19:30
Hey @clara-zi ! Great tests! Yes - so the range in the tooltip should be the actual range not "100%-1000%" as it was in the design. I just put that as an example. From your tests, I can see only one thing missing. Just going to clarify for the devs:

@MohammadPCh I think we are still missing the bottom tooltip on "unstake" - which should only appear if the user has some GIV that is locked.

![image](https://user-images.githubusercontent.com/75490971/184429892-b45bfef1-26ab-4a20-b22e-fae44cfd9539.png)

**Comment by divine-comedian** [comment] 2022-08-15 00:01
> Hey @clara-zi ! Great tests! Yes - so the range in the tooltip should be the actual range not "100%-1000%" as it was in the design. I just put that as an example. From your tests, I can see only one thing missing. Just going to clarify for the devs:
> 
> @MohammadPCh I think we are still missing the bottom tooltip on "unstake" - which should only appear if the user has some GIV that is locked.
> 
> ![image](https://user-images.githubusercontent.com/75490971/184429892-b45bfef1-26ab-4a20-b22e-fae44cfd9539.png)

I already implemented this and you can see it while testing on https://givpower.vercel.app/givfarm

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184559742-60e0e547-6478-46ba-9361-f04c3c73bb85.png">

**Comment by franculio** [comment] 2022-09-16 17:23
Tested on https://givpower.vercel.app/givfarm

All the tooltips seems to be where they should be:

Unstake
<img width="685" alt="Captura de Pantalla 2022-09-16 a las 19 19 45" src="https://user-images.githubusercontent.com/79286405/190695428-715d8c84-fca3-478f-8d64-c6cd0f08fd0c.png">

APR's

<img width="685" alt="Captura de Pantalla 2022-09-16 a las 19 20 46" src="https://user-images.githubusercontent.com/79286405/190695691-b1db8ea8-eb0c-4c47-ba13-aa17bd281dc5.png">

<img width="890" alt="Captura de Pantalla 2022-09-16 a las 19 20 56" src="https://user-images.githubusercontent.com/79286405/190695752-7fe8da8c-ddd3-4a8a-884d-69054cfeb57c.png">

Moving this to testing passed

**Closed** 2022-11-21 14:34 UTC
Labels: GIVeconomy
