### ISSUE TITLE
On Mobile (iOS) - token balance on Giveth shows as zero, when the actual wallet balance is >0

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4225] opened 2024-05-31 18:44 UTC
This was reported by a user in discord through a support ticket. On Optimism, Polygon when using iPhone or iPad, they see their token balance as 0, when they have funds in their wallet. They don't have this issue on Celo or Arbitrum.

On Optimism (Mobile) - user reported having OP.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e7ab536e-4db2-4799-98b6-5b8d32af269e)

On Polygon (ipad) - user has MATIC.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1b6cabfb-706f-41a6-acb0-79033b83cab1)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/d8397a70-2931-49da-8f0a-66ed3ae15060)

**Comment by laurenluz** [comment] 2024-05-31 18:46
@MohammadPCh assigning you as FE lead & @divine-comedian as dapp lead - not sure who should take this.

**Comment by divine-comedian** [comment] 2024-05-31 19:40
@maryjaf Can you test this out on iPhone and see if you can replicate it? 

@laurenluz - Did the user tell us what wallet and which browser they were using when they experienced this error?

**Comment by laurenluz** [comment] 2024-05-31 19:41
They said they tried from both safari and metamask browser

**Comment by divine-comedian** [comment] 2024-06-01 02:00
JFYI I tested this real quick on Android with metamask and chrome and didn't have any issues with token balances showing on the app, could be an iOS issue or a temporary glitch with MM or RPCs - but we'll see if the issue can be reproduced.

**Comment by LuminaEnvision** [comment] 2024-06-02 10:44
GM Giveth
Thank you @laurenluz & @divine-comedian 

I did two things: connected to Zerion in Safari - same story, in Zerion browser itself too

Then I didn’t know what to do anymore, closed my VPN and was sure I wouldn’t be able even open Giveth. Surprisingly, Giveth.io opened and moreover read my balance on Zerion. So I don’t know looks like VPN was a reason of this strange bug, or how else can you explain it?

**Comment by LuminaEnvision** [comment] 2024-06-03 18:02
Yes @divine-comedian it all worked 😅

**Comment by divine-comedian** [comment] 2024-06-03 23:13
Okay so looks like a VPN issue, not something we can handle on the Giveth side, going to close this one.

**Closed by divine-comedian** 2024-06-03 23:13 UTC
Labels: bug, P0
