### ISSUE TITLE
Allow user to manually input monthly donation amount

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4034] opened 2024-04-19 15:32 UTC
In addition to using the slider bar, users should be able to manually input an amount that they would like to donate monthly to a project. We'll need to design the space for the input box as well as space for error messages such as when a user inputs an invalid amount.

#### input box
![Recurring  Existing stream](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/407eae9a-6f57-4b71-9d37-d003807c50fc)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=25703%3A24430&mode=design&t=kPe3q2rrBfT37wsQ-1

#### On out of bounds error
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d67b6d6a-968b-47ed-8d4b-c70500ecdaa3)

When the user inputs an amount the slider bar reacts. 

need some error handling or input number boundaries based on available stream balance

# Acceptance Criteria

- [x] User can enter a value up to 7 digits, including decimal numbers when making a recurring donation
- [x] slider bar reacts and moves to a point corresponding with value input
- [x] when user enters an invalid number - such as more than their stream balance or an amount that would cause their stream balance to run out in < 1 month - a warning message is shown beneath the slider bar/input field component
- [x] same criteria above passes when modifying a recurring donation

**Comment by Tosinolawale** [comment] 2024-05-02 18:39
![Recurring  3rd donation](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/b86bbeaa-2038-4238-a6ad-6202742534c3)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=25682%3A22002&mode=design&t=kPe3q2rrBfT37wsQ-1
All its edge cases in the Figma file @divine-comedian

**Comment by kkatusic** [comment] 2024-05-20 07:29
Little update about this, we manage to put notification, input field, but getting problem with existing input field component on manually adding amount.

**Comment by maryjaf** [comment] 2024-05-22 12:24
- [ ] the showing amount on "Confirm your donation" modal isn't based on donation amount to a project and giveth that is entered by user , please take a look on below screen record @kkatusic @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9d1cc578-1bf7-4c69-a419-e113e30f0883

**Comment by maryjaf** [comment] 2024-05-22 12:53
> * the showing amount on "Confirm your donation" modal isn't based on donation amount to a project and giveth that is entered by user , please take a look on below screen record @kkatusic @MohammadPCh

It happens only one time, in the other tests it was as expected

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5a615bca-b47c-4230-b108-d8f3f38e9968

**Comment by divine-comedian** [comment] 2024-05-22 14:36
@maryjaf  - 

Please also test modify existing recurring donation

**Comment by maryjaf** [comment] 2024-05-22 14:40
I’ve tested both create recurring and modify recurring donation

**Comment by divine-comedian** [comment] 2024-05-24 15:01
@kkatusic - Can you check this please and see if there is a solution, if you need more info please coordinate with maryjaf

**Comment by maryjaf** [comment] 2024-05-27 05:48
> * [ ]  the showing amount on "Confirm your donation" modal isn't based on donation amount to a project and giveth that is entered by user , please take a look on below screen record @kkatusic @MohammadPCh
> 
>  Screen.Recording.2024-05-22.at.3.44.57.PM.mov
> @divine-comedian and @maryjaf what is exact problem?

@kkatusic this was the problem 
But  it doesn't happen to me again, I'm not sure what was the reason but in other tests I couldn't reproduce it 
I'll check more today, if it won't happen I close this bug 
Please you also check it

**Comment by maryjaf** [comment] 2024-05-27 05:55
There is another bug, please take a look 
- [ ] 2- 
-based on below pic the available balance is  0.099009 
-I set 0.0001 for donate to the project 
-I change the amount from 0.0001 into 0.00001
I got error :This is the maximum you can donate monthly, top-up your stream balance to donate more!

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5667cc40-714f-4969-b371-eba3256cdf87

**Comment by divine-comedian** [comment] 2024-05-27 14:23
@maryjaf - I think you are making a mistake on the flow, I think it is working correctly.

1. you want to deposit 0.0001 ETH 
2. set recurring donation for 0.0001 ETH per month to given project (100% of the amount you are depositing)
3. change deposit amount to 0.0001 ETH 
4. receive error because you want to donate more monthly than you will deposit into your stream balance

**Comment by kkatusic** [comment] 2024-05-27 16:21
> > * [ ]   the showing amount on "Confirm your donation" modal isn't based on donation amount to a project and giveth that is entered by user , please take a look on below screen record @kkatusic @MohammadPCh
> > 
> > Screen.Recording.2024-05-22.at.3.44.57.PM.mov
> > @divine-comedian and @maryjaf what is exact problem?
> 
> @kkatusic this was the problem But it doesn't happen to me again, I'm not sure what was the reason but in other tests I couldn't reproduce it I'll check more today, if it won't happen I close this bug Please you also check it

I tested with ETH test tokens and xGIV tokens everything is working fine, maybe @MohammadPCh you can also check is some summary values mismatched when you click **_DONATE_** button, it should be same

**Comment by kkatusic** [comment] 2024-05-27 16:23
> There is another bug, please take a look
> 
>     * [ ]  2-
>       -based on below pic the available balance is  0.099009
>       -I set 0.0001 for donate to the project
>       -I change the amount from 0.0001 into 0.00001
>       I got error :This is the maximum you can donate monthly, top-up your stream balance to donate more!
> 
> 
> Screen.Recording.2024-05-27.at.9.11.49.AM.mov

@divine-comedian is right with this, _Stream amount_ and _Available_ amount isn't same, stream amount is amount that you dedicated to the all recurring donatio, and available amount is amount of that token inside your wallet. See image bellow.

Let me @maryjaf if some issue still exist on your side and thx for testing ;)

![wb_2C04E9DE](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/cac6622f-25b9-4290-80fc-2e10062e03e8)

**Comment by kkatusic** [comment] 2024-06-12 10:07
@divine-comedian you can close this issue

**Closed** 2024-06-12 14:13 UTC
Labels: SuperFluid, P2
