### ISSUE TITLE
P0- Transaction failed during load testing party.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3599] opened 2024-01-10 15:09 UTC
Transaction failed before the Metamask extension even popped up for a signature.
Chrome browser
1 USDC.e on Polygon
I also chose to give 5% to Giveth

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/9fe6776e-921a-4029-8269-d73a7de903f3)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/9f970298-f1a9-4c0b-a0a9-f0208f1608b2)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/d24fca42-30b6-4fee-9142-33c3322f6604)

@aminlatifi @laurenluz 
Let me know if you have other questions!

**Comment by aminlatifi** [comment] 2024-01-10 15:19
Nothing as a sign of error is here. Those red lines are either requests to sentry (log collector) blocked by browser or preflight requests failure which is out of our control and related to your connectivity and vercel.
@MohammadPCh like to know your thoughts here as well.

**Comment by MoeNick** [comment] 2024-01-10 16:07
The SaveDonation error before signature means frontend dropped something, maybe could not get the price or could not connect to web3modal

**Comment by jainkrati** [comment] 2024-02-05 13:24
@MohammadPCh could you spend few minutes to debugging this issue with @WhyldWanderer . Post that please share your findings here and confirm if it needs to be fixed on FE or BE

**Comment by MohammadPCh** [comment] 2024-02-08 13:47
@WhyldWanderer Is it happening again? please ping me in discord if it's happening for you.

**Comment by MohammadPCh** [comment] 2024-02-08 13:49
@divine-comedian could you please test it too?

**Comment by MoeNick** [comment] 2024-02-08 14:29
It's not happening all the time, but it was the main bug the users were reporting during Polygon Round and the previous one. 
I guess we could not find the route cause and did not find a chance to debug it with a user.

**Comment by MohammadPCh** [comment] 2024-02-11 09:34
Thanks @MoeNick. I spoke with @WhyldWanderer, and she informed me that the issue isn't occurring again for her. Therefore, we can close this specific issue and shift our focus to another one related to the general problem.

**Closed by MohammadPCh** 2024-02-11 09:34 UTC
Labels: bug, P0

**Comment by MoeNick** [comment] 2024-02-11 09:38
@MohammadPCh 

This happened again yesterday
@brichis reported here

https://discord.com/channels/679428761438912522/861692942645067777/1205934233806315611
