### ISSUE TITLE
STG| bug in showing "This token is eligible for GIVbacks" in donation page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3153] opened 2023-09-05 04:45 UTC
**Describe the bug**
based one first pic this account is in the purple list but in donation page this field **"walletAddressIsPurpleListed: false"** is set false and I see that my token is eligible for GIVbacks

**Expected behavior**
It should be shown that "This token is not eligible for GIVbacks."
**Screenshots**
<img width="964" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7f9b346a-cb5b-480e-a3be-4dda69be8a62">

<img width="1412" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4c234d6f-e813-4490-a725-6d89214c2818">

@mohammadranjbarz

**Comment by maryjaf** [comment] 2024-02-22 11:10
based on pic 2 that the response of backend is false, I think this problem should be checked by backend
On the other hand, this issue is old and may not need to be developed
and may be closed with a small review by @mohammadranjbarz

**Comment by alireza-sharifpour** [comment] 2024-02-22 11:12
> based on pic 2 that the response of backend is false, I think this problem should be checked by backend On the other hand, this issue is old and may not need to be developed and may be closed with a small review by @mohammadranjbarz

@jainkrati

**Comment by jainkrati** [comment] 2024-03-06 13:42
@CarlosQ96 could you take a quick look .. may be spend not more than 30 min as this is only to rule out the root cause of issue being presnet in FE or BE

**Comment by divine-comedian** [comment] 2024-08-30 15:09
@maryjaf - can we check if this issue still persists? if not them let's close it

**Closed** 2024-09-01 06:41 UTC
Labels: bug, P2, Dev Research
