### ISSUE TITLE
no $value for WETH donation

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#1300] opened 2022-08-03 17:01 UTC
0.1 WETH donation made to Diamante Bridge - donation appears in donation list but there is no conversion to $value. Other donations in the list show conversion to $. This probably means that this WETH donation has not been aggregated in the donation total?

[](url
<img width="1357" alt="Screen Shot 2022-08-02 at 6 20 18 PM" src="https://user-images.githubusercontent.com/100724132/182666232-1456ab2e-ad87-4115-804b-859ed01b601f.png">
)

**Comment by MoeNick** [comment] 2022-08-03 17:12
@CarlosQ96 can u pls take a look?

**Comment by CarlosQ96** [comment] 2022-08-03 17:20
On it!

**Comment by CarlosQ96** [comment] 2022-08-04 04:13
I debugged as much as I could but could not find the root cause or reproduce the issue. I am leaning towards one of our libraries "Monoswap" failed to fetch the price in a given time. But I could not find any log to confirm this.

For now I fixed manually the donation and donated too 😄

**Comment by clara-zi** [comment] 2022-08-04 10:18
Thank-you @MoeNick for picking up the issue so quickly. Thank-you @CarlosQ96 for quick fix. I have emailed the donor to let them know the issue is fixed. I am closing issue.

**Comment by MoeNick** [comment] 2022-08-04 10:21
Thanks @clara-zi fir reporting, lets keep this issue to find the route cause.

**Comment by clara-zi** [comment] 2022-08-11 18:49
If $value was in correct - does that mean that the GIVbacks allocated for this donation are also incorrect? Who would be best to tag? @MoeNick

**Comment by CarlosQ96** [comment] 2022-08-11 18:51
I can take a look @clara-zi

**Comment by MoeNick** [comment] 2022-08-15 06:32
Ahh, Sorry @clara-zi for that, I was assuming you QAed it, so if you need anyone to take a look, please put it in QA before closing.

**Comment by mohammadranjbarz** [comment] 2022-08-15 13:51
https://discord.com/channels/679428761438912522/928813033600475207/1008734613067280414

**Comment by CarlosQ96** [comment] 2022-09-01 02:34
@mohammadranjbarz @MoeNick I released the hotfix to prod. Moving to QA/UAT. Or should I move to done?

**Comment by CarlosQ96** [comment] 2022-09-01 02:34
We should probably wait.

**Comment by clara-zi** [comment] 2022-09-09 11:33
Hi. Can you please confirm if the givbacks are now allocated for this donation? @CarlosQ96 @MoeNick. Thanks.

**Closed** 2023-01-24 21:53 UTC
Labels: bug
