### ISSUE TITLE
Projects not showing up my account when they are unlisted

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#887] opened 2022-06-07 13:59 UTC
Project wasn't listed and was not showing up for the user.
![image](https://user-images.githubusercontent.com/74267818/172399063-0fea1238-b75b-4ffe-b625-c14ff6b96f96.png)

As soon as I listed it, it showed up.

I think that the projects should show here even if they are not listed so that the user can easily find them without knowing the slug.

**Comment by MoeNick** [comment] 2022-06-07 15:28
I have unlisted projects in my list. Are you sure @WhyldWanderer ?
![image](https://user-images.githubusercontent.com/80677512/172420170-ae9bcc23-6f8c-4ff3-b698-da5526c677e4.png)

Is it happening for you?

**Comment by MoeNick** [comment] 2023-09-25 08:28
I think if we have only one unlisted project in an account it won't show up. 
Can you reproduce it @maryjaf ?

**Comment by maryjaf** [comment] 2023-09-25 08:57
I can see all of my projects with unlisted or waiting for review  in my project tab

**Comment by MoeNick** [comment] 2023-09-28 14:03
closing this as we cant reproduce it.

**Closed by MoeNick** 2023-09-28 14:03 UTC
Labels: bug
