### ISSUE TITLE
Join page cards styling

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#643] opened 2022-05-01 04:32 UTC
Fix Join page card styling in order to make it more like the design.

**Comment by ascode94** [comment] 2022-05-01 04:35
The problem is in the subscription card and the size of subscribe button and also we have empty space in the right side of the cards.
![Screen Shot 2022-05-01 at 9 04 16 AM](https://user-images.githubusercontent.com/48887817/166132356-dc6d8c4b-5a92-4010-9fde-64dfec2251f3.png)

**Comment by divine-comedian** [comment] 2022-05-23 16:52
looks much cleaner! 

styling issues seem to be resolved, moving to DONE!
![image](https://user-images.githubusercontent.com/67759413/169869719-8cb5bdd2-c540-4366-a843-22a2f32dd031.png)

**Closed** 2022-08-08 07:18 UTC
