### ISSUE TITLE
Changes in single project card

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#922] opened 2022-06-13 14:21 UTC
## Design resources

- **Default state**, when users didn't apply for a verified badge yet

[Default card](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=9977%3A206281)

- **Under review card**, After users applied for the badge and we are still reviewing it.

[ Under review](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10031%3A193419)

- **Rejected**, When there's a problem with user data or anything that cause the rejection!

[Rejected card](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10031%3A193571)

- **Verified state**, When everything's fine and the project is eligible to have a Verified badge.

[Verified state card](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10031%3A193497)

**Comment by divine-comedian** [comment] 2022-07-18 18:06
testing on `https://giv-verification.vercel.app/`

I can see on the project cards the verification status successfully for when a project is rejected, however some other things don't seem to be working properly. 

![image](https://user-images.githubusercontent.com/67759413/179573927-b67976a6-a59e-4afd-8352-bee8746c532e.png)
For a successfully verified project the "please contact support" should be removed. 

Another thing I can't seem to successfully see the "Request Sent" status. I've completed the verification form multiple times

![image](https://user-images.githubusercontent.com/67759413/179574198-0a4d44f8-06f1-4a46-85f2-ec895c33b43d.png)

however the card on my project does not change from 'resume verification'

<img width="1339" alt="Screenshot 2022-07-18 at 12 04 33" src="https://user-images.githubusercontent.com/67759413/179574412-e2bf342e-781f-4274-95b7-d903b2900666.png">

---

lastly I would suggest some text changes.

"Verify status" should be "Verification status"

and "Please contact support team" should be "Questions? Contact Support"

**Comment by RamRamez** [comment] 2022-07-19 09:39
I've submitted my project (slug: `test-hi-5`) for verification but `projectVerificationForm.status` is still `draft`.
I think backend doesn't update the status.
@mohammadranjbarz Could you please take a look?

**Comment by mohammadranjbarz** [comment] 2022-07-19 09:43
> I've submitted my project (slug: `test-hi-5`) for verification but `projectVerificationForm.status` is still `draft`. I think backend doesn't update the status. @mohammadranjbarz Could you please take a look?

I added a feature in admin bro to can make submitted forms `draft` , for testing this feature I just make on of your forms `draft` in admin panel, so I think it's the reason, but for making sure, please submit it again and check if it's still draft

**Comment by RamRamez** [comment] 2022-07-19 11:10
@mohammadranjbarz The problem is still there

![image](https://user-images.githubusercontent.com/73441857/179736397-3e1575f6-2597-415c-84a2-3f72938ddc2d.png)

![image](https://user-images.githubusercontent.com/73441857/179736454-5456566a-6039-4ca1-a7f8-5d2ad4403727.png)

**Comment by RamRamez** [comment] 2022-07-19 11:11
@mohammadranjbarz the second problem is when I pass the step `managing funds`, it doesn't give me the checked badge.

![image](https://user-images.githubusercontent.com/73441857/179736824-d26738f8-3b66-4cf8-9352-b8c8cef72de2.png)

**Comment by mohammadranjbarz** [comment] 2022-07-19 13:53
@divine-comedian 
We had some issues due making forms draft by admin, maybe it affect your test cases as well, can you test the whole scenario again? (including `makeEditbaleByUser` forms in admin panel, submit --> make editable by user in admin --> submit --> reject/confirm in admin), all these scenario should be tested

**Comment by RamRamez** [comment] 2022-07-19 14:56
@divine-comedian Fixed in PR #1162:
1. remove `please contact support` for verified projects
2. change `verify status` to `verification status`
3. change contact support text to `Questions? Contact Support`

**Comment by divine-comedian** [comment] 2022-07-19 16:09
> @divine-comedian Fixed in PR #1162:
> 
> 1. remove `please contact support` for verified projects
> 2. change `verify status` to `verification status`
> 3. change contact support text to `Questions? Contact Support`

wonderful! let me know when it is merged and I will test again

**Closed** 2022-07-20 05:48 UTC
Labels: good first issue
