### ISSUE TITLE
Reduce requests to subgraph for GIVeconomy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4375] opened 2024-07-03 15:08 UTC
As discussed in the GIVeconomy call on Jul 2 and before, we are making too frequest requests to the subgraph for giveconomy related things.

@MohammadPCh @aminlatifi have discussed it and determined a solution! can you guys put more info and assign the appropriate person? 

cc @RamRamez

**Comment by MohammadPCh** [comment] 2024-07-04 11:22
Ok, I can take it based on what we talked about on the call.

**Comment by laurenluz** [comment] 2024-07-16 11:36
Hey @MohammadPCh Just checking in on this - do you have all the context you need?

**Comment by laurenluz** [comment] 2024-07-17 14:22
@mohammadranjbarz maybe you can follow up

**Comment by mohammadranjbarz** [comment] 2024-07-18 06:59
@MohammadPCh  @RamRamez  Can you give us an update about this issue?
Does it have any blockers?

**Comment by MohammadPCh** [comment] 2024-07-22 14:46
@geleeroyale Thanks for following up. I was on leave for about two weeks. It’s almost done, and I’ll try to finish it by the end of today or tomorrow.

**Comment by MohammadPCh** [comment] 2024-07-23 13:49
@geleeroyale We merged this feature into staging. Can you monitor the subgraph service and check the request volume?

**Comment by MohammadPCh** [comment] 2024-07-23 13:51
@maryjaf It's ready to test. we reduced the subgraph queries and refactored the fetching of them, you can test the GIVeconomy and related values and make sure values are ok and the UI is updating well too.

**Comment by maryjaf** [comment] 2024-07-24 06:50
I'm checking the GIVeconomy flows 
until now there is no problem for example in **stake** flow but in console log I see lots of errors
I'm not sure it is exactly related to this change or not, I thought share it in this comment with you @MohammadPCh 

![image](https://github.com/user-attachments/assets/e6de96f7-8ef6-41b0-bcc8-d9ee9c5c4165)

**Comment by maryjaf** [comment] 2024-07-24 07:04
- [ ] I think I had some locked GIV token but I see "Locked GIV detail" is disabled 
0xcd192b61a8Dd586A97592555c1f5709e032F2505

could you please take a look?
![image](https://github.com/user-attachments/assets/4ea17cf6-c981-4e64-bfee-63c734091c3c)

**Comment by geleeroyale** [comment] 2024-07-24 08:12
> * [ ]  I'm checking the GIVeconomy flows
>   until now there is no problem for example in **stake** flow but in console log I see lots of errors
>   I'm not sure it is exactly related to this change or not, I thought share it in this comment with you @MohammadPCh
> 

1 - it is looking for a goerli endpoint that does not exist anymore - we should factor this out/replace it with a network like sepolia
2 - Sadly it is a bit hard to monitor requests from staging. I will need to wait until it is merged to production to see an effect (only paid requests are being tracked by the graph)

**Comment by maryjaf** [comment] 2024-07-24 08:22
- [ ] 2-
- I tap on "Harvest" on GIVstream tab
- I confirm transaction
- I see errors in console log and "GIVstream Rewards" modal is loading 


https://github.com/user-attachments/assets/10d52a27-a676-4819-bb00-da0e5e17f4b4

**Comment by maryjaf** [comment] 2024-07-24 08:26
- [ ] 3-
I have no GIVback reward, could you please add it manually for my user, to be tested
@MohammadPCh @aminlatifi 

0xcd192b61a8Dd586A97592555c1f5709e032F2505

**Comment by maryjaf** [comment] 2024-07-24 09:30
- [ ] 4- it seem sth is wrong in FOX Flowrate 
- I see the "Harvest FOX" button is enabled 
- by tapping on it and then confirm transaction
- I got an error 


https://github.com/user-attachments/assets/30138110-78d9-4ba1-9a8b-4da3e8e6757c

**Comment by MohammadPCh** [comment] 2024-07-30 11:36
@geleeroyale for item 2, as you can see we need HTTPS address for the subgraph endpoint.

**Comment by MohammadPCh** [comment] 2024-07-30 13:59
@maryjaf I fixed all the issues that I could. let's have a call and talk about remaining because I couldn't reproduce them.

**Comment by divine-comedian** [comment] 2024-07-30 14:32
We are getting some minified react errors on prod 
![image](https://github.com/user-attachments/assets/1cec1933-c3ea-4e58-915d-a1d015262985)

@MohammadPCh mentioned that @geleeroyale & devOps team might need to upgrade connections to https to remove these erros.

**Comment by geleeroyale** [comment] 2024-07-30 16:41
Still the issue is unclear from the devops side. Which connection should be upgraded? We only use secure connections.

**Comment by MohammadPCh** [comment] 2024-07-31 12:38
Thanks, @geleeroyale. It looks like the issue I encountered was temporary.

**Comment by MohammadPCh** [comment] 2024-07-31 12:39
@divine-comedian could you please create another issue for this? thanks

**Comment by maryjaf** [comment] 2024-07-31 14:18
- [ ] When user completes harvest flow, the UI isn't updated and it takes some time , in this time user can taps again on harvest and see the previous  amount for harvest
please take a look on below screen record @MohammadPCh 

https://github.com/user-attachments/assets/73cec7e7-8ecd-459f-ad58-8f90d8194ecf

**Comment by MohammadPCh** [comment] 2024-08-01 06:18
Thanks @maryjaf, Nice catch, but it's not related to these changes, could you please create a new issue for this? Thanks

**Closed** 2024-08-30 14:32 UTC
Labels: devops, P2
