### ISSUE TITLE
GIVpower Boosting | Make projected rank update dynamically

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1904] opened 2022-12-07 14:53 UTC
From GIVeconomy call, we want to have projected rank show impact immediately (or as fast as possible).

Planning to make a hack in the frontend & build and API.

@MohammadPCh & @aminlatifi have a plan. Notes from GIVeconomy call are [here](https://www.notion.so/giveth/GIVeconomy-Development-on-December-7-2022-1ad033fbcd664323842d607df453c3ee)

cc @moenick @maryjaf

**Comment by laurenluz** [comment] 2022-12-07 20:17
cc @CarlosQ96 @GriffGreen

**Comment by laurenluz** [comment] 2022-12-08 15:42
https://github.com/Giveth/impact-graph/pull/755

**Comment by maryjaf** [comment] 2022-12-09 16:14
Please check this scenario @MohammadPCh @aminlatifi 
I boosted a project(The Foundation for Enhancing Communities) that didn't have a boost, and according to the boost amount, the expected rank is correctly displayed as 22.
But I expected that the current project, which has a rank  22(Cascades Raptor Center) and the following ranks will decrease by one rank(22->23/23->24/....)
But as you can see in the picture, it is unchanged for rank 22 and 25
But some like 23 and 24 are calculated correctly
I think there is a problem here that the expected rank for all projects is not calculated correctly
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/111529185/206743808-543c549d-597b-44ec-a16d-a2bb39831022.png">
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/111529185/206743983-c31c5a05-009b-45d3-b6e1-e7bf09d84cce.png">
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/111529185/206744735-e073ba0c-b8b6-40d2-b984-88cf7bb45d5b.png">
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/111529185/206744461-52008745-5a05-40d1-b49c-3c48eea25f77.png">
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/111529185/206744903-c00e6259-2dcb-480b-b5a5-d6172808c1af.png">

**Comment by maryjaf** [comment] 2022-12-09 19:00
3- I think we have another problem because for this project (and some project else) https://giveconomy.vercel.app/project/greater-vancouver-food-bank
more than 3 round the  current rank =10 projected round =11

**Comment by aminlatifi** [comment] 2022-12-09 19:21
> Please check this scenario @MohammadPCh @aminlatifi I boosted a project(The Foundation for Enhancing Communities) that didn't have a boost, and according to the boost amount, the expected rank is correctly displayed as 22.
> 
> <img alt="image" width="1270" src="https://user-images.githubusercontent.com/111529185/206743808-543c549d-597b-44ec-a16d-a2bb39831022.png">
> 
> But I expected that the current project, which has a rank 22(Cascades Raptor Center) and the following ranks will decrease by one rank(22->23/23->24/....) But as you can see in the picture, it is unchanged for rank 22 and 25 <img alt="image" width="1224" src="https://user-images.githubusercontent.com/111529185/206743983-c31c5a05-009b-45d3-b6e1-e7bf09d84cce.png"> <img alt="image" width="1365" src="https://user-images.githubusercontent.com/111529185/206744903-c00e6259-2dcb-480b-b5a5-d6172808c1af.png">
> 
> But some like 23 and 24 are calculated correctly <img alt="image" width="1244" src="https://user-images.githubusercontent.com/111529185/206744735-e073ba0c-b8b6-40d2-b984-88cf7bb45d5b.png"> <img alt="image" width="1315" src="https://user-images.githubusercontent.com/111529185/206744461-52008745-5a05-40d1-b49c-3c48eea25f77.png">
> 
> 1- I think there is a problem here that the expected rank for all projects is not calculated correctly 2- After a few minutes the current rank of "The Foundation for Enhancing Communities" changed from "--" into "25" and i didn't understand why 25? <img alt="image" width="1390" src="https://user-images.githubusercontent.com/111529185/206747009-87599060-c12f-45b2-9a97-227ad54ae32f.png">

It's normal 😄 
As it's implemented, we calculate the instant power of a project and will tell the user where the project will stand if it has this power for a full round. Actually nothing changes in the db, and they are run independently. 
For example if a project with rank 22 has power 10,000, and rank 21 has power 12,000; 
the future rank of projects with the instant power of 11,000, 10,000 and 11,000 will be 22. Because they assume in the next ranking calculation nothing is touched and only they will have that power. So they will be 22.

```
2- After a few minutes the current rank of "The Foundation for Enhancing Communities" changed from "--" into "25"
and i didn't understand why 25?
```
Probably the project didn't have that power (corresponding to rank 22) for all the previous round!

**Comment by aminlatifi** [comment] 2022-12-09 20:10
> 3- I think we have another problem because for this project (and some project else) https://giveconomy.vercel.app/project/greater-vancouver-food-bank more than 3 round the current rank =10 projected round =11
> 
> <img alt="image" width="1358" src="https://user-images.githubusercontent.com/111529185/206778106-836ff053-671d-4cd1-97d9-e39552fd55bc.png">

Nice catch @maryjaf 
The project total power is "totalPower": 59077.433625, but in frontend when we query we use 59077.43 (the rounded number). @MohammadPCh @alireza-sharifpour Can we fix it in the frontend? or needs some support in the backend?

**Comment by MohammadPCh** [comment] 2022-12-09 20:45
@laurenluz @maryjaf  @aminlatifi  I increased the accuracy of decimal numbers. So it must be fixed.

**Comment by aminlatifi** [comment] 2022-12-09 21:09
> @laurenluz @maryjaf @aminlatifi I increased the accuracy of decimal numbers. So it must be fixed.

No, it didn't solve the issue. We must solve it fundamentally!
The problem is in rounding in the backend and the frontend. We must set some precision for calculating givpower on the backend, and conform to the same policy on the frontend.
I suggest having a precision of 2 fraction digits! Going to make the backend PR now.

**Comment by aminlatifi** [comment] 2022-12-09 23:15
I made these PRs
https://github.com/Giveth/giveth-dapps-v2/pull/1921
https://github.com/Giveth/impact-graph/pull/757

The backend has issues with tests, it's late here maybe Carlos can found the issue and solve them. If that goes through the frontend will be ready for review

**Comment by aminlatifi** [comment] 2022-12-10 05:56
Backend PR is merged, the fronend must work fine. But I made a PR to improve it
https://github.com/Giveth/giveth-dapps-v2/pull/1921, waiting for review by @MohammadPCh or @alireza-sharifpour

**Comment by MohammadPCh** [comment] 2022-12-10 09:45
@aminlatifi I've set it to 10 in the frontend (59077.xxxxxxxxxx)

**Comment by maryjaf** [comment] 2022-12-10 13:59
Please mention me when the changes are ready to retest on Giveconomy barnch @aminlatifi @MohammadPCh @alireza-sharifpour

**Comment by alireza-sharifpour** [comment] 2022-12-11 05:20
> Please mention me when the changes are ready to retest on Giveconomy barnch @aminlatifi @MohammadPCh @alireza-sharifpour

The Amin's PR on the Frontend is merged and it's on Giveconomy branch.

**Comment by maryjaf** [comment] 2022-12-11 15:00
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111529185/206911130-7be7aab3-385d-4a7f-9621-ac898c43c034.png">
Two projects are shown as #11 ranked @aminlatifi @alireza-sharifpour

**Comment by maryjaf** [comment] 2022-12-11 15:11
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/111529185/206911578-e62f78f7-6aa0-4fd4-a16b-2c71651dfc56.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111529185/206911605-a9c05c9b-4408-4663-825c-9c63050be04d.png">

at the same time the projected rank for two project with different givpower  is calculated "21"!

**Comment by maryjaf** [comment] 2022-12-11 15:14
> > <img alt="image" width="1440" src="https://user-images.githubusercontent.com/111529185/206911130-7be7aab3-385d-4a7f-9621-ac898c43c034.png">
> > Two projects are shown as #11 ranked @aminlatifi @alireza-sharifpour
> 
> @maryjaf Are their total power different?

No, it is the same for both 
If Give Power was the same, the  Rank of both projects would be the same, is the expected result?
I am not sure that they are exactly the same in decimal

**Comment by aminlatifi** [comment] 2022-12-11 15:25
> > > <img alt="image" width="1440" src="https://user-images.githubusercontent.com/111529185/206911130-7be7aab3-385d-4a7f-9621-ac898c43c034.png">
> > > Two projects are shown as #11 ranked @aminlatifi @alireza-sharifpour
> > 
> > 
> > @maryjaf Are their total power different?
> 
> No, it is the same for both 49,287.45 If Give Power was the same, the Rank of both projects would be the same, is the expected result? I am not sure that they are exactly the same in decimal

@maryjaf Yes, they must have the same rank. In backend we limited the power precision to 2 fraction decimals

**Comment by maryjaf** [comment] 2022-12-11 15:41
> <img alt="image" width="1437" src="https://user-images.githubusercontent.com/111529185/206911578-e62f78f7-6aa0-4fd4-a16b-2c71651dfc56.png">
> 
> <img alt="image" width="1438" src="https://user-images.githubusercontent.com/111529185/206911605-a9c05c9b-4408-4663-825c-9c63050be04d.png">
> 
> at the same time the projected rank for two project with different givpower is calculated "21"! Plz check this @aminlatifi

Thanks @aminlatifi 
Please take a look at this as well

**Comment by aminlatifi** [comment] 2022-12-11 17:22
> > <img alt="image" width="1437" src="https://user-images.githubusercontent.com/111529185/206911578-e62f78f7-6aa0-4fd4-a16b-2c71651dfc56.png">
> > <img alt="image" width="1438" src="https://user-images.githubusercontent.com/111529185/206911605-a9c05c9b-4408-4663-825c-9c63050be04d.png">
> > at the same time the projected rank for two project with different givpower is calculated "21"! Plz check this @aminlatifi
> 
> Thanks @aminlatifi Please take a look at this as well

If their future total power is more than or equal power of the 21st project and less than the 20th project, that value is correct. @maryjaf Is it the case/

**Comment by maryjaf** [comment] 2022-12-11 18:57
> > > <img alt="image" width="1437" src="https://user-images.githubusercontent.com/111529185/206911578-e62f78f7-6aa0-4fd4-a16b-2c71651dfc56.png">
> > > <img alt="image" width="1438" src="https://user-images.githubusercontent.com/111529185/206911605-a9c05c9b-4408-4663-825c-9c63050be04d.png">
> > > at the same time the projected rank for two project with different givpower is calculated "21"! Plz check this @aminlatifi
> > 
> > 
> > Thanks @aminlatifi Please take a look at this as well
> 
> If their future total power is more than or equal power of the 21st project and less than the 20th project, that value is correct. @maryjaf Is it the case/

Total Givpower of "Jewish Federation of Northern New Jersey, Inc" was 8084 Giv and "Cascades Raptor Center" was 6206 Giv but for both of them the projected rank = 21

**Comment by maryjaf** [comment] 2022-12-12 07:20
According to the conversation we had with @aminlatifi , with the new changes, it has been accepted that the calculated projected rank is not necessarily correct @laurenluz

**Closed** 2022-12-15 23:40 UTC
Labels: GIVeconomy, GIVPower
