### ISSUE TITLE
"Likes" on Project updates

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1817] opened 2022-11-14 16:17 UTC
As a donor, I would like to show my support for a project's updates when they post them.

I get emails as a donor when a project updates, and, as I am curious, I always go to check them out. I'd love to be able to interact with the project at this moment, but "liking" the update.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b2a93a8f-d82f-4f53-9871-d516c05856b9)

**Comment by divine-comedian** [comment] 2024-04-17 16:33
Duplicate of #1616 - lets follow up there.

**Closed by divine-comedian** 2024-04-17 16:33 UTC
Labels: Design, Feature Request
