### ISSUE TITLE
I didn't mean to publish my project, but it published, or maybe not?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#360] opened 2022-03-25 19:03 UTC
I made a test project to play with the preview, didn't save it, didn't hit publish... because I wanted to see how the "draft" feature worked...

but then I got an email saying it was published!

I'm confused about the way drafts are supposed to work, and think it is a bug that this somehow got published after I only looked at a preview.

@pkretzschmar @mateodaza

**Comment by laurenluz** [comment] 2022-03-25 19:04
Like... what does "waiting for review" mean?  Does the "x" mean it has not been published? Is this an autopilot error? I'm so confused.
![image](https://user-images.githubusercontent.com/75490971/160185318-52681cb4-dbe6-4737-a9a7-0fbbe5ab357f.png)

**Comment by laurenluz** [comment] 2022-03-25 19:08
Shouldn't "waiting for review" actually say "draft" in the case of me having not published it yet... 

It should only say "waiting for review" if I published and it has not yet been reviewed by an admin, no?

**Comment by pkretzschmar** [comment] 2022-03-25 19:57
@laurenluz according to what I talked with @CarlosQ96, when you create a project, it becomes unlisted for 30 minutes or so. In #287 , @MoeNick requested to use this label to indicate that.

**Comment by laurenluz** [comment] 2022-03-25 20:11
I think the project after being created should stay unlisted until reviewed by admin bro. "Waiting for review" makes sense in this case, but I think the "x" means my project is not active... i.e. not published in this case 🤔

If it is a draft, it should perhaps say "draft"

**Comment by laurenluz** [comment] 2022-03-25 20:11
Lmk if you find out that it was published somehow!

**Comment by CarlosQ96** [comment] 2022-03-25 20:12
I meant for staging those 30 minutes, I’ll look into it.

**Comment by MoeNick** [comment] 2022-03-25 23:19
For this issue, we should first change the email of draft creation, then if project status =null, we may not automatically change listing status to listed if not reviewed by admins.

**Comment by CarlosQ96** [comment] 2022-03-29 05:03
I shouldn't have published the project, after looking at the cronjob code. It only checks active projects not drafts. So something else triggered the publish. 
Will keep looking and will debug with Mateo or Pedro.

**Comment by laurenluz** [comment] 2022-03-29 13:45
but tbh, I don't think it is actually published 🤔 doesn't the "x" mean it is inactive? I think it just triggered the emails saying it was published... and had the "waiting for review" label... but was always inactive.

**Comment by CarlosQ96** [comment] 2022-03-29 23:48
Ok so Mateo helped me and this occurs on the creation of the project. 
The cronjob is working fine. 

I got two options, disable the email/event on creation for drafts or create a different event for drafts.

**Comment by CarlosQ96** [comment] 2022-03-29 23:52
@divine-comedian Asked Mitch and I kind of agree that drafts shouldn't have a email. It's literally that a draft for the future or might be discarded, no need for notifications.

Since it's a draft it will never be automatically published.

**Comment by MoeNick** [comment] 2022-03-29 23:52
@CarlosQ96 
I suggest removing event on creation and add another event to send email while changing from draft to active

**Comment by MoeNick** [comment] 2022-03-29 23:53
So publish only means changing from draft to active. Creation is not matter anymore.

**Comment by CarlosQ96** [comment] 2022-03-29 23:54
@MoeNick The implementation uses the same activateProject Mutation, which sends the email project Activated. 
This is already being reused, or should we create a different event.

**Comment by MoeNick** [comment] 2022-03-30 00:04
We have: 
- Draft to Active
- Deactivated to Active

I think 1st one is creation (publish) and second one is only kinda activation. 

So emails is not necessary when we create a project in draft status (let's remove it) , but we should send it while we change draft to active (which us publish)

In the case if changing deactivated to active, I don't think so that we send and email. Right? @CarlosQ96

**Comment by CarlosQ96** [comment] 2022-03-30 00:10
@MoeNick actually you are right, there is an event from deactivate -> active but it doesn't send any email. 

So ill add a new event for the draft -> active state. And set up a new email (this is done on segment, Mitch can help me with that)

**Comment by MoeNick** [comment] 2022-03-30 00:13
@CarlosQ96 pls also consider the user might directly save the project as active and push the publish button. So normally the email should be sent.

**Comment by laurenluz** [comment] 2022-03-31 18:42
I created a draft on staging and didn't get an email... but are emails actually even triggered from staging environment? I think this needs to be tested on live, no?  @CarlosQ96

**Comment by divine-comedian** [comment] 2022-03-31 23:03
I was able to turn emails on temporarily for staging - One thing we had to change is the journey inside autopilot. Since autopilot listens for the segment event by name, changing `Project created` to `Draft published` means that it was no longer seeing the segment event and thus no longer sending the email. 

I created a duplicate journey of Project created for Draft published so there won't be any weird gap of emails not being sent between making this change and when it is pushed to production.

![image](https://user-images.githubusercontent.com/67759413/161163148-3a68e35d-44a6-47cf-a3c9-f277add345f8.png)

and I can confirm I received an email when I hit the `publish project` button on my project. 

![image](https://user-images.githubusercontent.com/67759413/161163436-4dc28e05-d173-4fdb-9f6c-20150af0900f.png)

I will ping rodri so we can make a quick fix to the banner to say `Project published!`

**Comment by CarlosQ96** [comment] 2022-03-31 23:09
@divine-comedian Thanks a lot for this. I was gonna talk to you soon about it.
Basically if someone creates a draft -> it wont sent the Project created, because its a draft. Skipping the email.
So when someone activates de draft, it will send this new email with event Draft published.

**Comment by divine-comedian** [comment] 2022-03-31 23:23
sorry I forgot to test another part of the issue - following lauren's suggesttions we should indicate somewhere on the project list if it is a draft stage or 'unpublished'. I would agree the most logical place to put it is in the `listing` column - the project is not `waiting for review` if it is still being drafted -
![image](https://user-images.githubusercontent.com/67759413/161164587-751b1a07-7513-4cc2-b431-9051e2566310.png)
 
if status=draft then this text in the column should say `draft` - like dis 

![image](https://user-images.githubusercontent.com/67759413/161165248-c75dff48-92e1-44e5-b317-73757d1a4fe4.png)

**Comment by MoeNick** [comment] 2022-04-04 12:07
@divine-comedian 
the project can be active but waiting for the review to get listed, so it's not the case. 
we only have Active column up there to say true/false - it was a design decision, so even the project is deactivated/canceled / draft it shows a crossmark instead of the checkmark there. 
@mosaeedi do you have any idea seems it's not user friendly in draft status not to show them

**Comment by MoeNick** [comment] 2022-04-18 12:08
https://github.com/Giveth/giveth-dapps-v2/pull/527/files/c2abfab54145a994135c43b743dd34cde371d79b..2999ab9f2c5025ad34d389f11cc772e5de7c9bd1

This is new design for better user  understanding

**Comment by divine-comedian** [comment] 2022-04-18 13:24
this looks resolved as well in issue #399 

moving to done!

**Comment by MoeNick** [comment] 2022-04-18 13:26
Yes sir.

**Comment by divine-comedian** [comment] 2022-04-18 13:27
okay moving to DONE

**Closed** 2022-07-20 12:21 UTC
