### ISSUE TITLE
Duplicate projects with the same slug

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2941] opened 2023-07-17 13:45 UTC
I am showing this project twice on the projects page. They have the same slug, the same wallet address but different ID's

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/c2574fe2-09ad-4229-94e5-d5d8dbeebae2)

https://giveth.io/project/eth-kipu

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/e34a9daf-a03a-4763-841e-30fdf8f8c232)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/09e16046-de39-4040-80d7-ea559ce0c229)

I don't think this should be possible.

**Comment by MoeNick** [comment] 2023-08-21 14:45
@divine-comedian can you take alook pls.

**Comment by MoeNick** [comment] 2023-08-21 14:46
@CarlosQ96 can we make it happen and how?

**Comment by mohammadranjbarz** [comment] 2024-03-20 14:38
@RamRamez  Do you work on this?

**Comment by RamRamez** [comment] 2024-03-20 23:17
@mohammadranjbarz I'm working on [#1176](https://github.com/Giveth/impact-graph/issues/1176), I think this one is duplicate and we can close this.
FYI @jainkrati

**Comment by RamRamez** [comment] 2024-03-21 10:59
we have no project with id = 2649
It seems we have deleted that duplicate project before.
@MoeNick I think we can close this issue and follow it up on https://github.com/Giveth/impact-graph/issues/1176

**Comment by jainkrati** [comment] 2024-04-10 13:22
closing this as duplicate of  Giveth/impact-graph#1176

**Closed** 2024-04-10 13:22 UTC
Labels: bug, P0
