### ISSUE TITLE
Trying manage addresses & add Goerli - it won't let me add the same address that I am already using for that project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2858] opened 2023-07-11 16:53 UTC
This COULD be because someone else is using this address for ANOTHER project on Giveth... but it seems unlikely... this is the same address that I have set for this project on Gnosis.

@MoeNick - who can look into this?
 
<img width="538" alt="Screenshot 2023-07-11 at 6 52 16 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1088fc14-a179-4741-b8d7-d28c520b8694">
<img width="548" alt="Screenshot 2023-07-11 at 6 52 43 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/79fd1706-c426-49ad-b3fd-961218bdda31">

**Comment by laurenluz** [comment] 2023-07-11 16:53
I'm testing on staging

**Comment by divine-comedian** [comment] 2023-08-14 05:58
It could be useful for the user to know WHICH project is already using that address - I don't know if it fixes the root problem but it is more informative. 

@mohammadranjbarz - Do these toast notifications come from the back-end?

**Comment by MoeNick** [comment] 2023-08-14 07:43
Yeah it comes from the backend @divine-comedian , 
1) I'd say let's try to reproduce it first. @maryjaf if you can take a look pls, I think we had this problem but ot's resolved, pls try it my account section not in edit project. 

2) if we could not reproduce it then we can search to find the address from other projects @mohammadranjbarz OR @CarlosQ96 if you have bandwidth

**Comment by mohammadranjbarz** [comment] 2023-08-14 13:10
> It could be useful for the user to know WHICH project is already using that address - I don't know if it fixes the root problem but it is more informative.
> 
> @mohammadranjbarz - Do these toast notifications come from the back-end?

Yeah this error comes from backend

**Comment by mohammadranjbarz** [comment] 2023-08-14 14:08
> > > Yeah it comes from the backend @divine-comedian ,
> > > 
> > > 1. I'd say let's try to reproduce it first. @maryjaf if you can take a look pls, I think we had this problem but ot's resolved, pls try it my account section not in edit project.
> > > 2. if we could not reproduce it then we can search to find the address from other projects @mohammadranjbarz OR @CarlosQ96 if you have bandwidth
> > 
> > 
> > I agree with you because it would not be possible base on the things I see in the codes, if @maryjaf can find to reproduce way it can be a great help
> 
> What would not be possible exactly?

Showing that error if you have used the address for the same project that you are adding the address to it

**Comment by maryjaf** [comment] 2023-08-15 05:08
It's related to test data
@mohammadranjbarz if you remember for this project all of addresses had been removed and one day we set this address from admin bro for "How many photos is too many photos?"

@laurenluz It's better that you'll edit and change this address and set your address on this

**Comment by MoeNick** [comment] 2023-08-16 11:55
So I can close this, @laurenluz pls let Ashley Nikola or even me edit your project on Admin, test data is corrupted

**Closed by MoeNick** 2023-08-16 11:55 UTC
Labels: bug
