### ISSUE TITLE
When a user doesn't have a Givers PFP we shoudn't tell them to view it on rarible (user page)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4170] opened 2024-05-17 17:34 UTC
at giveth.io/user/<address>
for a user with no Giver as their PFP, we still have this link there.. that goes to "undefined" on rarible.

we should comment that out. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1abbac19-c7ea-47f9-a8e8-7806bd9874f4)

**Comment by divine-comedian** [comment] 2024-05-17 21:24
@laurenluz - I couldn't reproduce this - could you provide the URL to the user profile where you experienced this? 

This is what I see on production: 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/0ed03a0f-9912-4d62-83e2-4599de732b2b)

**Comment by laurenluz** [comment] 2024-05-21 17:37
https://giveth.io/user/0x50418699cB44BfDa9c9afc9B7a0b0d244d8927D2

**Comment by divine-comedian** [comment] 2024-05-21 20:36
Nice catch! merged the fix on staging on https://github.com/Giveth/giveth-dapps-v2/commit/fe50d0ff03f37180d411ca3869d84bf8a1a65fb9

tested on all scenario

- public view | user with pfp but didn't set as profile
- private view | user with pfp but didn't set as profile
- public view | user with PFP set 
- private view  | user with PFP set 
- public view | user with no PFP set and doesn't own any 
- private view | user with no PFP set and doesn't own any 

everything seems to work as expected

**Comment by jainkrati** [comment] 2024-05-29 07:13
so can we mark this done?

**Comment by divine-comedian** [comment] 2024-05-29 15:46
> so can we mark this done?

I already marked this as done 8 days ago.. just needs to be merged to prod for it to be closed.

**Comment by jainkrati** [comment] 2024-05-30 08:53
@RamRamez in the FE release pls ensure this change goes to prod

**Closed** 2024-07-17 22:44 UTC
Labels: Done
