### ISSUE TITLE
PM verification UX after the revoked badge removed. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1497] opened 2022-09-14 13:20 UTC
if this project is active then now my projects says I have to verify my project. 

I do not have to add any updates or change anything in my project to continue with the re-verification process. I have to completely redo the verification process and submit again for review, in admin bro I see my project and can add back my verification badge and listed status.

This UX could use some improvements:

- the obvious fix is that as a project owner I am not forced to make any updates or edits to my project before re-applying for verification
- there should be more frontend indications to the project owner that their project was revoked and they need to re-apply
- it was a bit annoying that I had to redo my entire verification application

_Originally posted by @divine-comedian in https://github.com/Giveth/giveth-dapps-v2/issues/1367#issuecomment-1244522804_

**Comment by MoeNick** [comment] 2022-09-19 11:45
@CarlosQ96 @mohammadranjbarz 
to solve this problem, I think we have to change the status of the related verificationForm to draft, right after the project gets revoked badge. 
What do you think?

**Comment by mohammadranjbarz** [comment] 2022-09-19 11:52
> @CarlosQ96 @mohammadranjbarz to solve this problem, I think we have to change the status of the related verificationForm to draft, right after the project gets revoked badge. What do you think?

@MoeNick  Yeah I think it's really a good idea if we had a related verification form for that project ( because the older project doesn't have that), we change the status of certification form to `draft`

**Comment by mohammadranjbarz** [comment] 2022-09-27 12:51
@CarlosQ96  has implemented that and now it's on **Staging**

@maryjaf 
Test flow:
1. Create a project in https://staging.giveth.io
2. Create a verification form for that and summit it
3. verify verification form in admin panel , now project should be verified
4. call **Revoke badge** for this project in admin panel, then project should not be verfied anymore, and verification for of this project should get `draft`
5. Now you got https://staging.giveth.io and submit you verification form again
6. Verify verification form and then project should get Verified

Another flow:
This flow is mostly for older projects that don't have verification form
1. Create a project in https://staging.giveth.io
2. **Don't** submit any verification form for that and just go to admin panel and verify the project
3. Then after calling **Revoke badge** you should not get any error although project doesnt have any verification form


@MoeNick  @CarlosQ96  please correct me if I missed anything

**Comment by maryjaf** [comment] 2022-09-28 12:44
when select "revoke badge" from list of project, the status of verification change into **draft**
and page of detail project is shown as below:
![image](https://user-images.githubusercontent.com/111529185/192779878-c560ca07-f300-48dc-a8b4-711edc545a95.png)

but after that select "verify project" the verified field in list of project changes in to yes but status of project remains draft in  project verification form.
plz check this scenario @mohammadranjbarz

**Comment by CarlosQ96** [comment] 2022-09-28 13:40
I'll check this issue, thanks Maryjaf

**Comment by maryjaf** [comment] 2022-10-02 14:46
> I'll check this issue, thanks Maryjaf

Thanks @CarlosQ96 
Do we have any update about it?

**Comment by CarlosQ96** [comment] 2022-10-02 14:58
I haven't find the root cause yet. Will keep looking into it today.

One question:
Did the reviewer change to your user when you clicked "Verify Project"?

**Comment by CarlosQ96** [comment] 2022-10-02 14:58
@maryjaf

**Comment by maryjaf** [comment] 2022-10-02 17:27
> @maryjaf

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/111529185/193467581-4b14bb57-9ebc-463e-a22c-51788e6035c8.png">

**Comment by CarlosQ96** [comment] 2022-10-05 07:35
Related Pr fixing this https://github.com/Giveth/impact-graph/pull/678

**Comment by mohammadranjbarz** [comment] 2022-10-05 11:03
> Related Pr fixing this [Giveth/impact-graph#678](https://github.com/Giveth/impact-graph/pull/678)

@CarlosQ96  Merged
@maryjaf  you can test again

**Comment by maryjaf** [comment] 2022-10-08 05:37
Thanks, a problem related to verify project after revoke badge has been fixed, but now i see this:

when tap on revoke badge in project list for a verified project
the status of project changed to fraft correctly and the PM see "resume verification" in project detail
after that tap on "resume verification" below pic is shown 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/37bf6351-b003-437f-8112-5dc5d20e94d0)
plz check it @CarlosQ96 @mohammadranjbarz

**Comment by CarlosQ96** [comment] 2022-10-08 14:39
Hello @maryjaf I pushed a hotfix so you can test again!

I missed resetting terms and conditions back to false, and setting the form to the first step. 
This should reset it correct it.

**Comment by maryjaf** [comment] 2022-10-09 16:04
> Hello @maryjaf I pushed a hotfix so you can test again!
> 
> I missed resetting terms and conditions back to false, and setting the form to the first step. This should reset it correct it.

I tested again and It seems that the changes  haven't been deployed on staging.

**Comment by MoeNick** [comment] 2022-10-09 18:01
@CarlosQ96 would you please take a look?

**Comment by maryjaf** [comment] 2022-10-10 15:14
I think the changes are not on staging @CarlosQ96 @mohammadranjbarz 
Because when I revoke badge the project, it is as shown in the image below and the "resume verification" is not displayed.
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/2af67a20-8aa1-4ff9-beeb-ff65d396974c)

**Comment by CarlosQ96** [comment] 2022-10-10 15:22
Will double check today, thanks!

**Comment by CarlosQ96** [comment] 2022-10-11 06:14
@maryjaf I am testing but this project doesn't have a verification form related to it or created. So the image is actually correct, as even tho you revoked the verified boolean, there was no associated verification form to modify.

If the project had a verification form it would have shown -> resume.

**Comment by CarlosQ96** [comment] 2022-10-11 06:20
I added additional tests to validate making the project verification form DRAFT after revoking a badge.

**Comment by CarlosQ96** [comment] 2022-10-11 06:33
Revoking a project or using unverify, will reset the form to draft and the step to managing funds, also set terms and conditions as false.

**Comment by CarlosQ96** [comment] 2022-10-11 06:35
Maybe we can make a few scenarios and go step by step, to see where the bug is being generated. 

But according to the additional tests I added, this image shouldn't happen again. 

> Thanks, a problem related to verify project after revoke badge has been fixed, but now i see this:
> 
> when tap on revoke badge in project list for a verified project the status of project changed to fraft correctly and the PM see "resume verification" in project detail after that tap on "resume verification" below pic is shown ![image.png](https://camo.githubusercontent.com/37cef7bb1b6a3d29971a80fd4b30adfda70419e60449c7c1eefefcc7db44061f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f33376266363335312d623030332d343337662d383131322d356463356432306539346430) plz check it @CarlosQ96 @mohammadranjbarz

**Comment by maryjaf** [comment] 2022-10-14 12:37
I tested again after front changes and the problem has been fixed.
Now when the verified project is revoked by the admin, the status of the verification form changes to "Draft" and in the details of the project "resume verification" is shown and when tap on "resume verification" the below pic is shown:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c6428cee-ae37-4ee6-9b15-604d6f9298bd)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d83e4014-cba8-4fcb-9ea9-6a19c62fcd55)
@CarlosQ96 @MoeNick

**Closed** 2022-10-25 14:32 UTC
