### ISSUE TITLE
Project search function is nearly useless

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4120] opened 2024-05-06 10:31 UTC
**Describe the bug**
When trying to search for a specific project, Giveth does not return as expected. 
It seems that the search function will only return projects if you type the name of the project **exactly**, completely and including cases sensitivity. 

For example... when I search "digital", I get 0 projects found
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/de64b941-3079-476f-919e-cc845d2c257f)

When I search "street musician", I only get 3 Giving Block projects returned.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/3c3ec923-0552-4507-9216-1a4f5e261d5f)

Under both circumstances I would expect this project is shown in the search results in both cases:
https://giveth.io/project/digital-street-musician-doing-free-live-concerts

this is not the only project that I experience this with. Thankfully, I have access to the adminbro and can find projects that way but most users to not have this capability.

**To Reproduce**
1. Go to https://giveth.io/projects
2. search for "digital"
3. You will see that this project is not included in the results

**Expected behavior**
Giveth should pull results from all projects containing the word "digital" in their title or in their project description

**Comment by maryjaf** [comment] 2024-05-07 15:43
I've tested on STG and there is no problem in displaying projects related to the searched word 
But I got 500 error some times and api testing of search query has been failed in some request like as below pic @aminlatifi 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f9cb8297-e747-49dd-91e9-17a85cab7138)

**Comment by divine-comedian** [comment] 2024-05-07 19:27
I can see we are applying the sort by to the search results, maybe this is skewing things - I looked up street musician and this project ["Digital Street Musician"](https://giveth.io/project/digital-street-musician-doing-free-live-concerts) was shown way down in the results when it was really the closest match by keyword, but not the highest results perhaps when sorting by GIVpower

**Comment by aminlatifi** [comment] 2024-05-08 06:06
> I can see we are applying the sort by to the search results, maybe this is skewing things - I looked up street musician and this project ["Digital Street Musician"](https://giveth.io/project/digital-street-musician-doing-free-live-concerts) was shown way down in the results when it was really the closest match by keyword, but not the highest results perhaps when sorting by GIVpower

That's an important point. The way project search is implemented doesn't include matching scores in the sorting!! it only defines a cut-off for similarity and filter projects. They are still sorted by default sorting which is instant power I guess.

**Comment by maryjaf** [comment] 2024-05-08 06:30
I've run the test today and I haven't received 502 gateway timeout  @aminlatifi 
It seems there is no blocker for deploying 
but based on @divine-comedian comment,do we want to make a change or not necessarily now?

**Comment by aminlatifi** [comment] 2024-05-08 07:51
> I've run the test today and I haven't received 502 gateway timeout @aminlatifi It seems there is no blocker for deploying but based on @divine-comedian comment,do we want to make a change or not necessarily now?

Mitch request needs lots of work and it's out of the scope of this fix.
@divine-comedian

**Comment by divine-comedian** [comment] 2024-05-08 13:54
I think the original issue @WhyldWanderer posted was from the search query taking so long it would be killed - I was able to test and get results. 

@aminlatifi I think we can close this one and work out of the other, more specific issues, that you made, Is that okay?

**Comment by aminlatifi** [comment] 2024-05-08 21:13
> I think the original issue @WhyldWanderer posted was from the search query taking so long it would be killed - I was able to test and get results.
> 
> @aminlatifi I think we can close this one and work out of the other, more specific issues, that you made, Is that okay?

The change I made is only deployed on staging. If everything fine on staging, we can push it to master as well
https://github.com/Giveth/impact-graph/pull/1545

**Comment by divine-comedian** [comment] 2024-05-09 00:42
OK, we can move this to Done and include it in the next BE release

**Comment by divine-comedian** [comment] 2024-05-14 21:44
Hey @aminlatifi  @mohammadranjbarz 

I was testing this out on production after we merged the latest fixes... 

There is this project https://giveth.io/project/emergency-relief-fund-for-brazil-floods 

When I search for 'brazil' it doesn't show up in any search results.. something is still not working correctly with this feature.

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/803cb35a-c940-4c79-96a6-0fcfb0ad8a95

**Comment by maryjaf** [comment] 2024-05-15 06:58
With these changes and the previous changes that have been applied to the search mechanism and performance, the results have improved
For example, the exact name of the project should have been typed before, for example, if the word "mejan" was entered with a space on the stage environment, no result would be seen.
Or now the problem that Ashley mentioned in the search for the word "digital" has been solved.

But in general, the search mechanism still needs to be improved in order to see the maximum matching
@divine-comedian @aminlatifi

**Comment by aminlatifi** [comment] 2024-05-15 09:39
> @divine-comedian I found the issue. The similarity threshold, a variable set in db, resets on each db connection session. The default value is 0.3, we have configured it to be 0.1 but it resets to the default value. Working on it.

Related to https://github.com/Giveth/impact-graph/issues/1551

**Comment by divine-comedian** [comment] 2024-05-20 14:32
problem in DB, variable set by extension need to figure this one out @mhmdksh

**Comment by aminlatifi** [comment] 2024-05-20 16:30
Currently in the search query we have created, we used `similarity` filter based on the `pg_trgm.similarity_threshold` value, with a default value of 0.3.
The filtering section of the query is like this
```psql
	AND (
		"project"."title" % 'brazil emergency'
		OR "project"."description" % 'brazil emergency'
		OR "project"."impactLocation" % 'brazil emergency'
	)
```
This notation of filtering allow us to use similarity search with utilizing the indexes. Unfortunately, default threshold 0.3 is not enough to match expected projects and we have issues in changing that.

Today, I noticed using world_similarity filter with this notation allows us to utilize indexes 
```psgl
	AND (
		"project"."title" %> 'brazil emergency'
		OR "project"."description" %> 'brazil emergency'
		OR "project"."impactLocation" %> 'brazil emergency'
	)
```
Wold similarity probably is less flexible but gives higher ranks on exact matches.
The word similarity threshold default value is 0.6, but it would work out better for us. So I suggest changing the queries with word similarity like above and see whether it solves the problem or not.

**Comment by divine-comedian** [comment] 2024-05-21 13:17
@jainkrati  - who do you suggest could implement this for us to test it out on staging?

**Comment by RamRamez** [comment] 2024-05-22 12:52
@divine-comedian [this project](https://giveth.io/donate/emergency-relief-fund-for-brazil-floods) is deactivated and only active projects are returned from search results.

**Comment by aminlatifi** [comment] 2024-05-22 13:51
@RamRamez That project won't be listed even if it was listed.
With default similarity threshold (0.3) it's filtered.
<img width="835" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/5684607/17cca90f-c0da-4f27-a55e-ab5421879a60">
Instead word similarity gets higher values, so the project will pass 
<img width="877" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/5684607/6baa0101-c5a3-42ad-a658-1223361c4cf5">

**Comment by divine-comedian** [comment] 2024-05-22 14:38
I found another example here, looking for "ENS wayback machine" I search ENS and I get no results, searching for wayback however yields results 


https://github.com/Giveth/giveth-dapps-v2/assets/67759413/233e1dd1-cb93-4f81-b9e7-e115e59dcac1

**Comment by RamRamez** [comment] 2024-05-22 17:55
I've deployed Amin's suggestion for this issue on staging.
@maryjaf could you please test if Mitch's reported problem has been resolved or not?

**Comment by maryjaf** [comment] 2024-05-27 08:16
The project name that was searched by @divine-comedian was on prod 
I've tested some search item like a below video, it seems the problem has been resolved , is this expected result ? @divine-comedian

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5f2d3f46834d574277981b069d78dd45e1d65fe/Screen%20Recording%202024-05-27%20at%2011.37.44%E2%80%AFAM.mov)

**Comment by divine-comedian** [comment] 2024-05-27 14:42
I tested a bit on staging and couldn't find any big other than staging is REALLY SLOW AND CRASHES. 

I tried however using FUND and the "The Ellen Fund" was like the 7th result, while it was the only project that had "Fund" in its title, why does it happen? most of the other projects didn't have any likes or GIVpower boosting

**Comment by maryjaf** [comment] 2024-05-27 14:56
> I tried however using FUND

The showing projects by searching fund have "fund" in title or about or in category list (fundraising)

**Comment by jainkrati** [comment] 2024-05-29 12:50
@maryjaf can we mark it as done?

**Comment by maryjaf** [comment] 2024-05-29 13:23
> I've deployed Amin's suggestion for this issue on staging. @maryjaf could you please test if Mitch's reported problem has been resolved or not?

has this change been deployed on production? @RamRamez

**Comment by RamRamez** [comment] 2024-05-29 13:27
> > I've deployed Amin's suggestion for this issue on staging. @maryjaf could you please test if Mitch's reported problem has been resolved or not?
> 
> has this change been deployed on production? @RamRamez

Yes!

**Comment by divine-comedian** [comment] 2024-05-29 15:58
Just tested it out! looks like its working well enough, closing this issue.

**Comment by RamRamez** [comment] 2024-07-30 09:28
I'm reopening this issue as @WhyldWanderer has some tickets regarding a project is not found in search results.
![image](https://github.com/user-attachments/assets/0020ba7a-8905-4302-b60f-804a9e24c3e5)

**Comment by WhyldWanderer** [comment] 2024-07-30 11:16
Also there are 2 other projects who have noticed a similar issue.

its strange to me that when I search "codex" or "CODEX" on the projects page, I do not get this project at all:
https://giveth.io/project/codex

Similarity, when I search for "earth" or "EARTH", I do not get this project at all:
https://giveth.io/project/earth

It seems that the "$" sign keeps it from being searchable somehow. It seems that this would be something that we could account for? I think its disheartening for project owners when they search their project on the page and don't see it show up on the list.

I will keep an eye out as Im searching projects etc for use cases such as this and post any here that I find in the coming days in case that might be helpful.

**Comment by aminlatifi** [comment] 2024-07-31 08:41
> Also there are 2 other projects who have noticed a similar issue.
> 
> its strange to me that when I search "codex" or "CODEX" on the projects page, I do not get this project at all: https://giveth.io/project/codex
> 
> Similarity, when I search for "earth" or "EARTH", I do not get this project at all: https://giveth.io/project/earth
> 
> It seems that the "$" sign keeps it from being searchable somehow. It seems that this would be something that we could account for? I think its disheartening for project owners when they search their project on the page and don't see it show up on the list.
> 
> I will keep an eye out as Im searching projects etc for use cases such as this and post any here that I find in the coming days in case that might be helpful.

@WhyldWanderer I tested myself, those projects are listed but are not shown at the top! it's not a desirable behaviour but we know it will work like that.
FYI, in our backend we don't sort projects based on similarity score, the search result still is sorted based on givpower ranking.

**Comment by aminlatifi** [comment] 2024-07-31 08:43
> > Also there are 2 other projects who have noticed a similar issue.
> > its strange to me that when I search "codex" or "CODEX" on the projects page, I do not get this project at all: https://giveth.io/project/codex
> > Similarity, when I search for "earth" or "EARTH", I do not get this project at all: https://giveth.io/project/earth
> > It seems that the "$" sign keeps it from being searchable somehow. It seems that this would be something that we could account for? I think its disheartening for project owners when they search their project on the page and don't see it show up on the list.
> > I will keep an eye out as Im searching projects etc for use cases such as this and post any here that I find in the coming days in case that might be helpful.
> 
> @WhyldWanderer I tested myself, those projects are listed but are not shown at the top! it's not a desirable behaviour but we know it will work like that. FYI, in our backend we don't sort projects based on similarity score, the search result still is sorted based on givpower ranking.

@divine-comedian @WhyldWanderer if you want this requirement "Sort search result based on word similarity", it must be implemented.
cc @jainkrati

**Comment by divine-comedian** [comment] 2024-07-31 13:58
I can confirm I can also find both of those projects while using the search function, however they are pretty far down. My recommendations to those project owners is if their project is verified they can acquire some GIV and boost their project with GIVpower to show up higher in the search results. Even a tiny bit of GIVpower would put them very close to the top search results.

**Closed** 2024-08-27 15:00 UTC
Labels: P0, performance
