### ISSUE TITLE
GIV/xDAI farm - lots of claimable tokens right after staking

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#807] opened 2022-05-25 18:06 UTC
I made my LP on honeyswap and I go to stake it into the GIVfarm 

it shows 0 rewards 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/e85f6572-9d17-49dd-8e5e-b2a7bebac1a5)

I approve and stake my LP
and the UI updates and now I have over 100k tokens I can claim instantly... seems a bit much.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/a62374c6-c9b3-47bd-ad3a-8b0466d302a8)

I unstake half of my tokens and now my claimable amount is reduced by half and the streaming amount as well

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/39c28d9c-cb9f-4c42-bfe1-235c3e3e902d)

I claimed rewards and only ~16k GIV was sent to me, (from accumulated GIVbacks, GIVstream and the farm itself)
here's the tx - https://blockscout.com/xdai/mainnet/tx/0x0da054ef9198aed2ef00658204f9cabd6e269ed87aa698d954b9e08775276a57

**Comment by aminlatifi** [comment] 2022-05-27 14:07
@divine-comedian You are right, there was an issue in processing events on subgraph. When you unstake, your reward till unstake tx should be computed and saved, but it wasn't. It should be fixed by this 
https://github.com/Giveth/giv-token-subgraph/pull/62

But it's not the cause of the extraordinary reward (100K)!. I assume your machine time is incorrect or our time syncing mechanism doesn't work well. Can you check `timeDifference` value as below? Probably the application time is a lot ahead so it displays your reward in the future.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/5684607/170715229-f095aa54-fa86-4315-994d-d533b5ee9154.png">

**Comment by divine-comedian** [comment] 2022-05-31 18:44
> @divine-comedian You are right, there was an issue in processing events on subgraph. When you unstake, your reward till unstake tx should be computed and saved, but it wasn't. It should be fixed by this [Giveth/giv-token-subgraph#62](https://github.com/Giveth/giv-token-subgraph/pull/62)
> 
> But it's not the cause of the extraordinary reward (100K)!. I assume your machine time is incorrect or our time syncing mechanism doesn't work well. Can you check `timeDifference` value as below? Probably the application time is a lot ahead so it displays your reward in the future.
> 
> <img alt="image" width="744" src="https://user-images.githubusercontent.com/5684607/170715229-f095aa54-fa86-4315-994d-d533b5ee9154.png">

Checking on my computer the timeDifference is `825`

**Comment by divine-comedian** [comment] 2022-06-01 12:57
`950`

**Comment by divine-comedian** [comment] 2022-06-01 13:06
doesn't seem to be happening anymore, could it be because before I was the first person to provide LP into the farm, claiming all of the eligible rewards at once since the farm was deployed?

**Comment by aminlatifi** [comment] 2022-06-07 07:10
So I move it to done as has not occurred since

**Closed** 2022-08-08 07:21 UTC
