### ISSUE TITLE
All unique donors on archived rounds say "pending"  BUG

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4596] opened 2024-08-20 19:39 UTC
This can be seen at: https://giveth.io/qf-archive
We should show actual numbers for unique donors

![image](https://github.com/user-attachments/assets/89eed3e2-378d-4be3-9c88-50bcb4f9913c)

@CarlosQ96 who can check on this?

cc @koday1

**Comment by divine-comedian** [comment] 2024-09-23 14:40
@CarlosQ96 what's the update on this issue?

**Comment by maryjaf** [comment] 2024-09-23 14:48
It's not a bug until this field "Is Data Analysis Done" isn't checked it will be  shown pending, when this feature had been merged on prod I explained what should be done for previous rounds on the related channels

![Image](https://github.com/user-attachments/assets/fa5c95a2-5cc5-41ef-914f-f3d7a4730c17)

**Comment by divine-comedian** [comment] 2024-09-23 16:41
Thanks! @laurenluz please take a look here

**Comment by maryjaf** [comment] 2024-09-24 07:00
> > It's not a bug until this field "Is Data Analysis Done" isn't checked it will be shown pending, when this feature had been merged on prod I explained what should be done for previous rounds on the related channels
> 
> where was this conversation @maryjaf ?
> 
> and how is the unique donors number being calculated then?

https://discord.com/channels/679428761438912522/861692942645067777/1264552859433828352

**Comment by laurenluz** [comment] 2024-09-25 12:21
I see, looks like Kieran did not see that or did not do it. 

For future issues - anything related to QF - please loop me in @maryjaf 

I will update this is in admin bro...

Also create a new issue #4776 because this needs to be updated now.

**Closed** 2024-09-25 13:24 UTC
Labels: bug, P0
