### ISSUE TITLE
GIVbacks round on prod is saying we're in round 0(For chains that we dont have subgraph address for them in the config)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4601] opened 2024-08-21 14:19 UTC
not sure what round we're in but it's not 0!

@mohammadranjbarz can you help assign the right person?

![image](https://github.com/user-attachments/assets/034687e0-4ddb-46ed-b170-e58766c7c25f)

**Comment by mohammadranjbarz** [comment] 2024-08-21 14:20
It should have been your network problem and maybe some request has failed, because it shows me correct value


<img width="1435" alt="Screenshot 1403-05-31 at 5 48 48 in the afternoon" src="https://github.com/user-attachments/assets/bc14214d-5b6f-4cd0-9f4b-b7fe3dc3c5f1">

**Comment by laurenluz** [comment] 2024-08-21 17:16
it persists for me 🤔 
![image](https://github.com/user-attachments/assets/e8193460-3b57-4691-a84c-b704f7146d19)

**Comment by mohammadranjbarz** [comment] 2024-08-22 08:58
> it persists for me 🤔 ![image](https://private-user-images.githubusercontent.com/75490971/360015625-e8193460-3b57-4691-a84c-b704f7146d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTAyNDIsIm5iZiI6MTcyNDMwOTk0MiwicGF0aCI6Ii83NTQ5MDk3MS8zNjAwMTU2MjUtZTgxOTM0NjAtM2I1Ny00NjkxLWE4NGMtYjcwNGY3MTQ2ZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTRmODNkNTA4ZTM5NWQ0NDllNDA3NmJhODNiNDgyNDEzZjZlNmYyOTViMjY5MzE5OTk4NDc5ZjM3NGJkOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c0VD2jztBEDVpyKtZwfvDTPzvNBX8BC-kaoJJmJ__kI)

@geleeroyale It might be unrelated to this issue but it seems we dont have `NEXT_PUBLIC_SUBGRAPH_CLASSIC` in vercel Environment variables so it uses the `http://167.172.97.150:8000/subgraphs/name/giveth/etc` (
In the production.tsx it says to use that url if `NEXT_PUBLIC_SUBGRAPH_CLASSIC` not exists
```
	CLASSIC_CONFIG: {
		...classic,
		chainType: ChainType.EVM,
		gasPreference: {
			// Keep it empty for automatic configuration
		},
		subgraphAddress:
			process.env.NEXT_PUBLIC_SUBGRAPH_CLASSIC ||
			'http://167.172.97.150:8000/subgraphs/name/giveth/etc',
```
) and because it's not a https address Chrome blocks it.

**Comment by geleeroyale** [comment] 2024-08-22 09:02
@mohammadranjbarz Nice catch! But please advise. What would be the correct setting for the env value (which subgraph) - adding the vars is easy enough

**Comment by geleeroyale** [comment] 2024-08-22 09:10
@laurenluz Yes - I can confirm. You found a bug. It seems that the givbacks round is only displayed on networks: Ethereum, Gnosis, Op mainnet. I could observe the Givbacks round 0 bug on all other supported networks like Base, Celo, ETC, Arbitrum, zkEVM, and also when no network was connected (i.e. Safari on Ipad)

**Comment by mohammadranjbarz** [comment] 2024-08-22 09:12
> @laurenluz Yes - I can confirm. You found a bug. It seems that the givbacks round is only displayed on networks: Ethereum, Gnosis, Op mainnet. I could observe the Givbacks round 0 bug on all other supported networks like Base, Celo, ETC, Arbitrum, zkEVM, and also when no network was connected (i.e. Safari on Ipad)

Thanks @geleeroyale , yeah you are right, it's how we can reproduce it.
I will work on it

**Comment by mohammadranjbarz** [comment] 2024-08-22 09:35
We have the same problem here https://giveth.io/project/bahar-library-a-beacon-of-hope-in-ramin-village?tab=givpower

When connected to a chain that doesn't have subgraph address, it shows today date instead of correct end of the round date

<img width="1232" alt="Screenshot 1403-06-01 at 1 03 27 in the afternoon" src="https://github.com/user-attachments/assets/2f92de76-506b-4677-aeac-28078dce552b">

**Comment by geleeroyale** [comment] 2024-08-22 09:41
But guys - is this information supposed to be:
- different on chains?
- updated often?

Because then it would be ideal to just query one subgraph and cache the value until it needs an update (new round) instead of doing this for all chains with a live query that might fail due to subgraph support

**Comment by mohammadranjbarz** [comment] 2024-08-22 09:44
> But guys - is this information supposed to be:
> 
> * different on chains?
> * updated often?
> 
> Because then it would be ideal to just query one subgraph and cache the value until it needs an update (new round) instead of doing this for all chains with a live query that might fail due to subgraph support

As I checked for this specific field (startTime) it's same for all smart contracts so I did the same solution in #461  , just put the correct value as the default value, so in case it fails it would use the correct default value

**Comment by geleeroyale** [comment] 2024-08-22 09:50
> > it persists for me 🤔 ![image](https://private-user-images.githubusercontent.com/75490971/360015625-e8193460-3b57-4691-a84c-b704f7146d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTAyNDIsIm5iZiI6MTcyNDMwOTk0MiwicGF0aCI6Ii83NTQ5MDk3MS8zNjAwMTU2MjUtZTgxOTM0NjAtM2I1Ny00NjkxLWE4NGMtYjcwNGY3MTQ2ZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTRmODNkNTA4ZTM5NWQ0NDllNDA3NmJhODNiNDgyNDEzZjZlNmYyOTViMjY5MzE5OTk4NDc5ZjM3NGJkOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c0VD2jztBEDVpyKtZwfvDTPzvNBX8BC-kaoJJmJ__kI)
> 
> @geleeroyale It might be unrelated to this issue but it seems we dont have `NEXT_PUBLIC_SUBGRAPH_CLASSIC` in vercel Environment variables so it uses the `http://167.172.97.150:8000/subgraphs/name/giveth/etc` ( In the production.tsx it says to use that url if `NEXT_PUBLIC_SUBGRAPH_CLASSIC` not exists
> 
> ```
> 	CLASSIC_CONFIG: {
> 		...classic,
> 		chainType: ChainType.EVM,
> 		gasPreference: {
> 			// Keep it empty for automatic configuration
> 		},
> 		subgraphAddress:
> 			process.env.NEXT_PUBLIC_SUBGRAPH_CLASSIC ||
> 			'http://167.172.97.150:8000/subgraphs/name/giveth/etc',
> ```
> 
> ) and because it's not a https address Chrome blocks it.

Fixed in https://github.com/Giveth/devops/issues/257

**Comment by mohammadranjbarz** [comment] 2024-08-22 13:17
@laurenluz  @maryjaf It's fixed and deployed on Production, you can test it now
https://giveth.io/givbacks

**Comment by laurenluz** [comment] 2024-08-22 15:52
better!! 
![image](https://github.com/user-attachments/assets/0a063b1b-65a2-46eb-a6aa-802ca5e63097)

maybe @maryjaf if you can do a quick check on all chains & with wallet not connected... if that's all ok,  then I think we can close this.

**Comment by maryjaf** [comment] 2024-08-25 07:13
> maybe @maryjaf if you can do a quick check on all chains & with wallet not connected... if that's all ok, then I think we can close this.

I've checked and it works as expected.

**Closed by maryjaf** 2024-08-25 07:13 UTC
